### ISSUE TITLE
Módulo de Gestión de Costes

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PPD#1]
- Flujo de tareas comunes por producto (Solicitar a MAC el listado). Estimación del coste previsto y mes de finalización. Inserción de información en dolares, en ESP en €. Hacemos nosotros la conversión. 

- Coste real: La secretaria técnica introduce el coste real por item.

- Pestaña adicional en información de filial en el país de copy: **Proyecto de Viabilidad**.

- Excel resumen importe de producto. Contará el real si está introducido sino el estimado.

- Avisos con fechas el mes que se cumple. Aviso por email a la secretaria si está asignada y sino a MAC o Zenia. Si tiene que estar en marzo el 1 de abril enviamos email.

- Totalizados por filial. Sumatorio por item.

**Comment by minigoBinpar** [comment]
@MACEMP 

¿Tendrías el _Flujo de tareas comunes por producto_?

**Comment by MACEMP** [comment]
@minigoBinpar @CristianBinpar 
Esta información me la tiene que facilitar Alfonso, En cuanto disponga de ella te la facilito

**Comment by MACEMP** [comment]
[2016 PPD NUEVA SECCIÓN COSTES_DESGLOSE CAMPOS.xlsx](https://github.com/BinPar/PPD/files/538149/2016.PPD.NUEVA.SECCION.COSTES_DESGLOSE.CAMPOS.xlsx)
@CristianBinpar
