### ISSUE TITLE
INCORPORAR CAMPOS PRECIO PREVISTO EN PRODUCTO LIBRO ACREDITADO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#10]
Actualmente (06/10) solo aparecen los campos de precio definitivo por lo que la previsión de venta en el INFORME PLANTILLA PRESUPUESTO siempre será 0
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Aparecen sólo los precios definitivos porque fue lo que se pidió de forma específica para estos productos.

¿quieres que vuelvan a aparecer TODOS los campos precio previsto?
