### ISSUE TITLE
PPD: ORDEN DE APARICIÓN DE LOS AUTORES - NO RESPETA LA JERARQUIA EN LA PANTALLA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#101]
![image](https://cloud.githubusercontent.com/assets/22589031/20215757/c36b77e4-a816-11e6-9b64-764af274e55f.png)
En la visualización en pantalla no respeta el orden jerárquico de autoría. Debiera de mostrarlos con este orden.
Por otra parte, debiera de implementarse la posiblidad, ya comentada, de que los autores apareciesen en el orden que aparecen en la portada de la obra.
@CristianBinpar

**Comment by minigoBinpar** [comment]
Hola Ángeles,

Este sería el resultado final:
![image](https://cloud.githubusercontent.com/assets/20515815/20533144/db366e28-b0dc-11e6-8113-e5323dd1ef8f.png)

Con esto tendríamos el primer paso en lo relativo a ordenar por jerarquía. En la tarea #124 vamos a plantear el sistema de importancia dentro incluso de autores con categorías iguales para que los autores apareciesen en el orden que aparecen en la portada de la obra.
