### ISSUE TITLE
PPD: SOLUCION ENVÍO EXCESIVO DE MENSAJES

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#102]
Implementar un nuevo botón GUARDAR Y COMUNICAR además de el botón GUARDAR.
El usuario elegiría una de las dos opciones en función de la relevancia de la información introducida

![image](https://cloud.githubusercontent.com/assets/22589031/20216342/4b8d1274-a81a-11e6-81b4-142135b9348d.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Las secciones que permiten guardar o guardar y notificar son:

- Edición obra
- Edición de autor
- Edición producto
- Edición precios filial

Me han parecido las secciones dónde pudiera encajar mejor esta funcionalidad. Si lo ves útil en alguna otra sección dímelo y añado en un momento.

**Comment by MACEMP** [comment]
Paco Cotrina comenta: 
Es necesario que el doble botón en todas las secciones (fechas, marketing, gestión compra mínima...)
Gracias.Francisco J. Cotrina

@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
Listo. Añadido en todas las todas las zonas

**Comment by MACEMP** [comment]
Todavía no aparece el botón en beta . ¿Está subida la versión?
@minigoBinpar

**Comment by minigoBinpar** [comment]
No, ahora subo en un rato

**Comment by MACEMP** [comment]
Perfecto!
