### ISSUE TITLE
PDF PPD: NO APARECE EN PDF EL TEXTO INCORPORADO EN COMENTARIOS OBRA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#103]
![image](https://cloud.githubusercontent.com/assets/22589031/20217063/6590e43a-a81e-11e6-890f-885805646c75.png)
![image](https://cloud.githubusercontent.com/assets/22589031/20217100/91f024c8-a81e-11e6-98d2-ebd76f3e2758.png)
Obra Prometheus: Texto y Atlas de Anatomía 
@CristianBinpar

**Comment by minigoBinpar** [comment]
Solucionado
proxima subida
![image](https://cloud.githubusercontent.com/assets/20515815/20312898/584de14e-ab55-11e6-8266-90567face404.png)
