### ISSUE TITLE
FECHA PREVISTA PAIS IMPRESION NO APARECE EN FILIAL

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#105]
![image](https://cloud.githubusercontent.com/assets/22589031/20278704/0213d676-aaa6-11e6-94a0-e3fa545b3e79.png)
esto es lo que yo veo con FILIAL ESPAÑA (Producto libro MEDICINA DE URGENCIAS COPY MEX)
![image](https://cloud.githubusercontent.com/assets/22589031/20278753/29246e1a-aaa6-11e6-86d1-9ea63c5932a3.png)
Esto es lo que aparece en la pantalla de COPY MEX.
La fecha PREVISTA PAIS DE IMPRESIÓN tiene que aparecer en la información de todas las filiales, ya que quien la indica es el pais COPY. Las filiales no puede introducir esa fecha
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Podrías darme un libro de ejemplo con varias filiales? A me me responde correctamente

**Comment by MACEMP** [comment]
La imagen del issue:
Producto LIBRO : MEDICINA DE URGENCIAS copy MEX
En los datos de Filial España no toma la FECHA ESTIMADA PAIS DE IMPRESION
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP vale, al hacer cambios en el copy original cambiaba el resto de filiales, pero no tenía caracter retroactivo. 

Creo tenerlo ya controlado. Cuando suba versión acuerdate de probarlo con algun productofilial más.
![image](https://cloud.githubusercontent.com/assets/20515815/20311865/a6831afe-ab51-11e6-843e-a82bf6218a70.png)

![image](https://cloud.githubusercontent.com/assets/20515815/20311884/be74635c-ab51-11e6-88f5-79996f9dc3af.png)
