### ISSUE TITLE
EXCEL PRESUPUESTO: NO DESCARGAR PRODUCTOS "ALTA CATALOGO NO"

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#106]
En el Excel descargado no deben de aparecer los productos que no se incorporen al catálogo.
Por ejemplo, este producto aparece en el listado

![image](https://cloud.githubusercontent.com/assets/22589031/20303127/3e8a6b7c-ab2a-11e6-9c77-0b519bd3193f.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Estoy muy perdido con esta tarea. Puedes llamarme y vemos¿?

**Comment by minigoBinpar** [comment]
@MACEMP 

Listo. Próxima subia chekea
