### ISSUE TITLE
¿Cual es el origen de la base de datos de autores?

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#107]
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Se cargan desde la base de datos de ppd. Actualmente tenemos unos 300 registros. desconozco si se trata de una carga manual paulatina en el tiempo o una carga inicial de importancia en los origenes

**Comment by MACEMP** [comment]
¿se podría cargar un Excel? ¿Qué campos debería de tener el Excel?
@minigoBinpar
