### ISSUE TITLE
LIBROS ACREDITADOS: NO TOMA LOS PRECIOS PREVISTOS - EL MENSAJE ES INCORRECTO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#108]
La sección precios de libros acreditados no funciona correctamente.
- No toma el precio previsto, dejando a 0 el campo, a pesar de GUARDAR
- No refleja correctamente los datos en el mensaje
![image](https://cloud.githubusercontent.com/assets/22589031/20308961/66410c22-ab46-11e6-9724-93b46a4d7487.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
Listo. Subo versión en un rato

![image](https://cloud.githubusercontent.com/assets/20515815/20310051/bfd341c0-ab4a-11e6-875c-d57b10c0d2fd.png)
