### ISSUE TITLE
INCORPORAR NUEVO ITEM EN EL COMBO Estado de la obra en INFORMACIÓN DE PRODUCTO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#11]
![estado de la obra](https://cloud.githubusercontent.com/assets/22589031/19145650/397e8882-8bb0-11e6-8d54-e99c69da1ee4.PNG)
También se debería de cambiar la etiqueta y en lugar de : ESTADO DE LA OBRA, debiera de indicar ESTADO DEL PRODUCTO (realmente se refiere al producto y no la obra)
El nuevo item es Preproducción
@CristianBinpar

**Comment by minigoBinpar** [comment]
Añadido
