### ISSUE TITLE
MEJORA VELOCIDAD HOME

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#110]
Se han recibido comentarios sobre la lentitud en el buscador de la HOME.
También se comenta que el mensaje "no hay datos" tarda mucho en salir
@CristianBinpar

**Comment by minigoBinpar** [comment]
Se comprueba la mejora en la velocidad de respuesta en la HOME. Se reduce de 3-5 seg. por búsqueda a milésimas de segundo una vez generada la primera búsqueda de un término.
