### ISSUE TITLE
INCREMENTO DEL TIEMPO PERMITIDO DE ACTIVIDAD DEL PPD

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#111]
Varios usuarios solicitan el incremento del tiempo de desconexión del PPD. Actualmente si no hay actividad durante 10' se desconecta, lo que obliga al usuario a volver a resgistrarse.
En puestos como Atención al cliente (teléfono) es necesario que se mantenga abierto durante toda la jornada para evitar pérdidas de tiempo en acceder nuevamente desde la página de login
@CristianBinpar

**Comment by minigoBinpar** [comment]
Le hemos puesto 200 minutos en pro y beta. No debería de haber problemas al respecto
