### ISSUE TITLE
Edición en bloque de CREAR AUTOR y ordenación por orden de importancia

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#112]
Edición en bloque de CREAR AUTOR
actualmente hay que CREAR y GUARDAR los autores de forma individual, lo que genera un mensaje cada vez que se incorpora un nuevo autor. Este sistema es poco eficiente ya que requiere mucho tiempo de carga de datos y genera muchos mensajes. Hay obras que tienen más de 50 autores por lo tanto 50 mensajes generados.
ORDENACION AUTOR POR ORDEN ESTABLECIDO POR EL USUARIO
Varias filiales han reparado en el hecho de que los autores aparecen por orden alfabético en el Informe Planificación (TAMBIÉN EN LA PANTALLA DE OBRA) y en ocasiones aparecen NOMBRE/APELLIDOS o APELLIDOS/NOMBRE. (esto solo sucede en el Informe Planificación)
Habría que:
1. implementar el sistema que permita ordenar a los autores que tienen el mismo rol por el orden que establezca el usuario
2. modificar en el Informe planificación el campo AUTORIA para que, cuando se trata de autores con el mismo rol aparezcan en orden establecido por el usuario y no el "orden" que presenta actualmente
@CristianBinpar

**Comment by CristianBinpar** [comment]
@MACEMP Vamos a dividir este issue en 2, para tratarlos por separado.
