### ISSUE TITLE
GESTION COMPRA MINIMA: visualizacion datos en filial no copy & Gestión en bloque

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#113]
Actualmente las filiales no pueden visualizar los datos de COMPRA MÍNIMA, únicamente el país COPY.
Se solicita:
1. que aparezca EJEMPLARES DE COMPRAS MINIMAS en la información de filial. La edicion la realizará el Pais Copy.
2. que se pueda gestionar desde la tabla en lugar de acceder a cada uno de los datos de las filiales. Este sistema consume mucho tiempo en la carga de datos 
![image](https://cloud.githubusercontent.com/assets/22589031/20309710/4f9bd17a-ab49-11e6-98a4-e88fb89b7c84.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
Primera parte hecha:
![image](https://cloud.githubusercontent.com/assets/20515815/20519045/a63126b8-b0a1-11e6-9330-a8cc58ecb564.png)

La segunda requiere un desarrollo importante en cuanto a tiempo. Mejor sería crear una tarea a parte y estimar costes/necesidad
