### ISSUE TITLE
¿Cómo funcionan las alertas/mensajes en la pestaña VIABILIDAD?

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#114]
No he realizado ningún test de esta funcionalidad y no sé si funciona correctamente.
@CristianBinpar

**Comment by MACEMP** [comment]
La tarea de GITHUB en la que se describe es la nº 1
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
Esta montado de cara a la aplicación, nos queda arrancarla en la máquina. Este viernes reviso PPD con Cris y buscamos un hueco para iniciar

**Comment by MACEMP** [comment]
Las filiales ya están incorporando los datos en VIABILIDAD. Imagino que los mensajes no tendrán carácter retroactivo ¿verdad?
Alfonso está especialmente interesado en estas alertas.
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
Cierro tarea para no duplicar ya que tenemos la #74
