### ISSUE TITLE
CAMPO PVP SOCIOS: NO  HA DE SER OBLIGATORIO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#115]
Están empezando a cargar los datos de productos de formación por lo que empezaremos a recibir comentarios e "issues". Este es el primero.
Este campo PV SOCIOS no siempre existe por lo tanto no puede ser obligatorio.
![image](https://cloud.githubusercontent.com/assets/22589031/20342466/c862e976-abea-11e6-8e76-ed8fc32dc9ba.png)
No está señalizado con el asterisco
@CristianBinpar

**Comment by minigoBinpar** [comment]
Listo. Subo en breves
