### ISSUE TITLE
NO FUNCIONA EL BOTON + AÑADIR UNIVERSIDAD EN CAMPO FORMACION

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#116]
![image](https://cloud.githubusercontent.com/assets/22589031/20342678/afa3bb3a-abeb-11e6-9aeb-24a5d130d2c5.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
Solucionado. que todas las crisis sean asi :D
