### ISSUE TITLE
INFORMACION PRECIOS PRODUCTOS FORMACION

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#118]
Se solicita modificar el cálculo de los precios cuando se trate de los siguientes productos:
EXPERTO
MASTER
PROGRAMA DE FORMACION CONTINUADA
PROGRAMA DE ACTUALIZACION
CURSO ONLINE

Los campos:
PRECIO LOCAL ESTIMADO: Se introduce el dato de forma manual
PRECIO ESTIMADO INTERCOMPAÑIA: SIN DATOS
PRECIO ESTIMADO EXPORTACION: SIN DATOS
PRECIO ESTIMADO INTERNACIONAL: SIN CALCULO. Se introduce el dato de forma manual

LO MISMO SUCEDE CON LOS PRECIOS DEFINITIVOS

@CristianBinpar

**Comment by minigoBinpar** [comment]
Bien, creo que lo tengo controlado. 

Subo versión en un rato. Esta parte necesita buen testeo porque complicamos un poco las variables y quizás se me escape algo
