### ISSUE TITLE
ERROR EN LA INTRODUCCIÓN DE PRECIOS LIBROS ACREDITADOS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#119]
![image](https://cloud.githubusercontent.com/assets/22589031/20345597/2fd03eb2-abf8-11e6-96fa-251a0853ab75.png)
No permite modificar los campos. Los deja a 0.
@CristianBinpar

**Comment by minigoBinpar** [comment]
Listo. Proxima subida
![Uploading image.png…]()
