### ISSUE TITLE
INFORME PLANTILLA PRESUPUESTO: Utilizar formato MONEDA en la columna Total presupuestado filial (dolares)

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#12]
Utilizar el mismo formato en la columna "Total presupuesto filial (dólares)" que en la columna "Total presupuestado filial (moneda local)"
En la columna en dólares no permite la suma ya que tiene formato GENERAL y debiera de tener formato MONEDA como la columna en Moneda local.

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/20674965/085583b4-b58b-11e6-8ac9-f5eae2d98237.png)

He cambiado el formato para que se pueda operar con los datos de las celdas
