### ISSUE TITLE
NO APARECE EN LA PANTALLA DE INTRODUCCION DE DATOS EL PRECIO INTERCOMPAÑIA NETO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#120]
![image](https://cloud.githubusercontent.com/assets/22589031/20345698/aa5ab6d0-abf8-11e6-8094-151a4ec25723.png)
NO APARECE EN LA PANTALLA DE INTRODUCCION DE DATOS EL PRECIO INTERCOMPAÑIA NETO, SIN EMBARGO SI QUE APARECE EN EL MENSAJE QUE ENVÍA DE NOTIFICACIÓN.
Como recordatorio decir que el precio internacional parte del precio internacional del libro x 2, que no puede ser superior a 300 Usd, ni inferior a 120 USD. Esto funcionaba correctamente, pero ha dejado de hacerlo.

El precio intercompañia es el precio internacional multiplicado por 0,75
El precio NETO INTERCOMPAÑIA es el precio Intercompañia multiplicado por 0,30

Esto funcionaba correctamente cuando solo aparecían los datos de precios definitivos, al incorporar el bloque de previstos se ha estropado.
@CristianBinpar

**Comment by minigoBinpar** [comment]
Y si el libro no tiene establecido del precio internacional, que ocurre con el re cálculo?

**Comment by MACEMP** [comment]
Siempre tiene el precio internacional .
EL precio internacional es el precio del libro en papel multiplicado por 2
@minigoBinpar

**Comment by minigoBinpar** [comment]
El precio intercompañia y El precio NETO INTERCOMPAÑIA son campos no rellenables porque actúa el recálculo, no?

**Comment by minigoBinpar** [comment]
@MACEMP 

Vale Ángeles, te subo a beta.

Es importante revisar bien esta sección para asegurarnos que los recálculos se hacen bien cuando las filiales de producto libro y producto libro acreditado coinciden. Que el resto de productos responden bien sus recalculos y que en estos casos de libro acreditado todo es correcto.

Mis pruebas parecen indicar que todo bien, pero es bastante confuso este tema y quizás se me scape algo.

Quedo a la espera de que me confirmes lo que sea.

**Comment by MACEMP** [comment]
En la versión anterior calculaba  ambos precios, pero permitía la edición del dato propuesto
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
osea que la edición está permitida en ambos campos de libros acreditados  (precio intercompañia y El precio NETO INTERCOMPAÑIA) pero en caso de no introducir valor se activa el recálculo

es correcto¿

**Comment by MACEMP** [comment]
Hemos estado haciendo pruebas con el siguiente resultado:
- Los cálculos de la zona DEFINITIVO están correctos. Solo falta sombrear el campo DEFNIITIVO EXPORTACION
- Los cálculos de la zona ESTIMADO no están correctos. Falta sombrear el campo DEFINITIVO EXPORTACIÓN e incluir el campo PRECIO NETO DEFINITIVO INTERCOMPAÑIA (aparece en la zona DEFINITIVO)
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Listo. Está subiendo versión osea que en 5 minutos puedes probar todo

**Comment by MACEMP** [comment]
![image](https://cloud.githubusercontent.com/assets/22589031/20392733/8024b190-acd9-11e6-8eb3-d62d73526944.png)
PRUEBA COPY COLOMBIA FILIAL ESPAÑA
Solo permite introducir el primer campo tanto en estimado como en definitivo
No guarda los datos 
No calcula el campo PRECIO ESTIMADO/DEFINITIVO NETO INTERCOMPAÑI
@minigoBinpar @CristianBinpar

**Comment by MACEMP** [comment]
![image](https://cloud.githubusercontent.com/assets/22589031/20393457/4c230ec0-acdc-11e6-86f0-439c27c454f8.png)
PRUEBA COPY ESPAÑA FILIAL ESPAÑA PRODUCTO LIBRO ACREDITADO LLUSA
Aparece una línea blanca con el número 78 a la izquierda ¿?¿¿?
Los cálculos no son correctos en la zona ESTIMADO
El precio ESTIMADO internacional es el precio estimado internacional del LIBRO multiplicado por 2. El precio que indica no es el correcto ya que sería 77 x 2 = 154 y no 60 como indica
En la zona PRECIO DEFINITIVOS no calcula ni permite editar
Creo que hay que revisar todas las fórmulas 
@minigoBinpar @CristianBinpar

**Comment by MACEMP** [comment]
![image](https://cloud.githubusercontent.com/assets/22589031/20394359/7faaeff8-acdf-11e6-846d-41c9239ca8ab.png)
A la hora de guardar datos de precios en beta, se recibe este mensaje de error
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP  
Prueba otra vez que he actualizado

**Comment by minigoBinpar** [comment]
@MACEMP

Prueba otra vez que he actualizado (vol.2)

**Comment by MACEMP** [comment]
![image](https://cloud.githubusercontent.com/assets/22589031/20399600/eaa71860-acf1-11e6-810c-e6a1a649abce.png)
Respuesta con error 
@minigoBinpar

**Comment by MACEMP** [comment]
Otro error de conexión con el servidor
![image](https://cloud.githubusercontent.com/assets/22589031/20399643/10520700-acf2-11e6-9929-6abb4511e919.png)
@minigoBinpar

**Comment by MACEMP** [comment]
Superado el error de conexión con el servidor

Los cálculos de precios definitivos no son correctos. Las cantidades debieran de ser las mismas que las estimadas
![image](https://cloud.githubusercontent.com/assets/22589031/20399797/9edd3440-acf2-11e6-92ce-b169fc2da815.png)
@minigoBinpar

**Comment by MACEMP** [comment]
![image](https://cloud.githubusercontent.com/assets/22589031/20399838/ca581018-acf2-11e6-9799-3b93d64f3cba.png)
La opción marcada en amarillo en la imagen no funciona porque no permite editar ninguno de los campos de la zona DEFINITIVO. Antes sí que permitía. 
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Llámame, Ángeles
