### ISSUE TITLE
Edición en bloque de CREAR AUTOR

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PPD#123]
Edición en bloque de CREAR AUTOR
actualmente hay que CREAR y GUARDAR los autores de forma individual, lo que genera un mensaje cada vez que se incorpora un nuevo autor. Este sistema es poco eficiente ya que requiere mucho tiempo de carga de datos y genera muchos mensajes. Hay obras que tienen más de 50 autores por lo tanto 50 mensajes generados.

**Comment by CristianBinpar** [comment]
@MACEMP aprovecharemos el desarrollo de "Guardar y comunicar" también para la creación de autores y así no será necesaria la edición en bloque.

**Comment by minigoBinpar** [comment]
Editando autor
![image](https://cloud.githubusercontent.com/assets/20515815/21139956/c32d2efc-c135-11e6-956a-2ec67b37c552.png)

Nuevo autor:
![image](https://cloud.githubusercontent.com/assets/20515815/21139963/d0dc7102-c135-11e6-8f52-0bfcd75c9bc0.png)
