### ISSUE TITLE
ordenación por orden de importancia

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PPD#124]
ORDENACION AUTOR POR ORDEN ESTABLECIDO POR EL USUARIO
Varias filiales han reparado en el hecho de que los autores aparecen por orden alfabético en el Informe Planificación (TAMBIÉN EN LA PANTALLA DE OBRA) y en ocasiones aparecen NOMBRE/APELLIDOS o APELLIDOS/NOMBRE. (esto solo sucede en el Informe Planificación)
Habría que:

implementar el sistema que permita ordenar a los autores que tienen el mismo rol por el orden que establezca el usuario
modificar en el Informe planificación el campo AUTORIA para que, cuando se trata de autores con el mismo rol aparezcan en orden establecido por el usuario y no el "orden" que presenta actualmente

**Comment by minigoBinpar** [comment]
@MACEMP 

Hola Ángeles, ya subí versión a beta. Tienes una nueva sección de ordenar autores:
![image](https://cloud.githubusercontent.com/assets/20515815/20561726/47f7ecc8-b180-11e6-9a6d-440c3e3e65bb.png)

Faltan los estilos pero me interesa más testar la funcionalidad. ¿Si todo es correcto podemos decir que ordenar en las listas por esta nueva funcionalidad prima sobre la ordenación por rol?

**Comment by MACEMP** [comment]
Me encanta la nueva funcionalidad, a pesar de no tener estilos es muy intuitiva y fácil de usar.  
 A tener en cuenta:
- El orden ha de ser Apellido Apellido, Nombre. Ahora aparece Nombre Apellido Apellido
- Efectivamente, primará la ordenación que se realicé por ORDEN DE IMPORTANCIA, sin embargo, si no hay orden de importancia mantendrá la jerarquización actual.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/20626045/34205792-b317-11e6-9c3d-063beaeefabd.png)

Listo

**Comment by MACEMP** [comment]
¡qué bueno! ¿Cuando estará en productivo?
@minigoBinpar

**Comment by minigoBinpar** [comment]
En cuanto deis el visto bueno, subimos

**Comment by MACEMP** [comment]
Por mi parte está bien.
@minigoBinpar @CristianBinpar
