### ISSUE TITLE
EN LOS INFORMES SIGUE APARECIENDO OBRAS ELIMINADAS Y OBRAS "CATALOGO NO"

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#125]
![image](https://cloud.githubusercontent.com/assets/22589031/20423810/de382692-ad72-11e6-83f9-f0c76e124457.png)
Esta obra es CATALOGO NO y aparece en el Informe planificación
Lo mismo sucede con LIBRO CENTENARIO que está ELIMINADO y aparece en el listado
@CristianBinpar

**Comment by minigoBinpar** [comment]
Sigue apareciendo porque en la tarea #125 se cambiaba en presupuestos, no especificamos informe.

Ya lo he cambiado. En la próxima subida aparecerá.
