### ISSUE TITLE
Cerfificado de sitio seguro: Problema en Chrome al cargar fuentes en HTTP

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PPD#126]
Copio el mensaje original de aviso que nos envió Ángeles:
--

Hola,
Últimamente estamos teniendo problemas con Chrome y  la apertura de pestañas del PPD 
Aparece una advertencia, que al clicar indica “Cargar secuencias de comandos no seguras” si aceptas, el sitio aparece en ROJO como NO SEGURO (ver imágenes)
El problema reside en que muchos usuarios no se dan cuenta del mini aviso en rojo y no pueden acceder a las pestañas que se abren al clicar en el menú de la HOME y piensan que es un error del PPD, cuando no es así.
¿No se podría solucionar esto, ya que se trata de un sitio seguro?

--

@minigoBinpar te copio el error para que lo puedas revisar:

Mixed Content: The page at 'https://ppd.medicapanamericana.com/Vista/index?id=c01d06c5-20b4-4144-a0ef-36361cda991f' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Lato:300'. This request has been blocked; the content must be served over HTTPS.

**Comment by MACEMP** [comment]
![image](https://cloud.githubusercontent.com/assets/22589031/20453685/0dc460e6-ae2d-11e6-9686-edd92c812eca.png)
Sigue apareciendo el error
@CristianBinpar @minigoBinpar

**Comment by MACEMP** [comment]
Ya no aparece el icono de advertencia en Chrome
![image](https://cloud.githubusercontent.com/assets/22589031/20476442/47947e28-afd1-11e6-80fe-3609f9d4a4a8.png)
@minigoBinpar @CristianBinpar
