### ISSUE TITLE
CAMPO TIPO DE CONTENIDO EN PRODUCTO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#129]
Desde Marketing solicitan un informe en el que aparezca el TIPO DE CONTENIDO del producto.
Se trata de un nuevo campo que tendría 3 opciones: Consulta - Divulgativo - Texto

Este campo existió en la primera versión del PPD, pero ya no está.
¿Podría incorporarse? Estaría en el bloque INFORMACION DE PRODUCTO
@CristianBinpar

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/20677823/bfff603a-b594-11e6-81af-9280be4df616.png)

Listo
