### ISSUE TITLE
MENSAJE COMPRA MINIMA: SOLO INDICA LAS UNIDADES SOLICITADAS, NO LAS CONFIRMADAS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#130]
El mensaje de EJEMPLARES COMPRA MÍNIMA solo aporta el dato de COMPRA MINIMA SOLICITADA.
Cuando se confirman los ejemplares de COMPRA MÍNIMA, envía el mensaje con los datos de unidades solicitadas y no de unidades confirmadas.
![image](https://cloud.githubusercontent.com/assets/22589031/20491340/5da654c6-b011-11e6-88dd-35fd9e2a0f6a.png)
![image](https://cloud.githubusercontent.com/assets/22589031/20491447/b9979236-b011-11e6-9889-ffb350bb9318.png)
En las imágenes se ve que he confirmado 1600 unidades para España y sin embargo el mensaje indica SOLICITADAS ... 1650.
Cuando se confirman, el mensaje debiera indicar CONFIRMADAS y las unidades CONFIRMADAS
@CristianBinpar

**Comment by minigoBinpar** [comment]
Creo que ha quedado controlado. Ahora subo versión

**Comment by MACEMP** [comment]
Hay una errata en el texto del mensaje : an, necesita la hache
Le informamos que se han producido cambios en el apartado de COMPRA MINIMA:
En la filial México se ha solicitado una compra mínima de 300 unidad/es de las cuales se an confirmado 300 unidad/es
Detalles:
EAN: 9788498352054
AUTORES:
Manuel Llusá Pérez
Alex Merí Vived
TÍTULO PRODUCTO: Anatomía del Aparato Locomotor
TÍTULO OBRA: Anatomía del Aparato Locomotor
Nº EDICIÓN: 2
TOMO: 
Si lo desea, visite el siguiente enlace para obtener más información:
Pulse aquí para ver información disponible 


Cambios realizados por Ángeles Castro (macastro@medicapanamericana.es) 


@miguelBinpar

**Comment by minigoBinpar** [comment]
UF! Que horrible.

Corregido:
![Uploading image.png…]()

**Comment by MACEMP** [comment]
Sigue la errata
En la filial España se ha solicitado una compra mínima de 200 unidad/es de las cuales se _an_ confirmado 0 unidad/es
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
Perdón, no actualicé la sección de emails. En unos minutos actualizo
