### ISSUE TITLE
Mejorar sistema de filtros en Informes y Servicio novedades

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PPD#131]
Propuesta de nuevo filtrado a consensuar con @MACEMP e implementación

**Comment by CristianBinpar** [comment]
Incluye #20 por lo que la cerramos y continuamos por aquí

**Comment by minigoBinpar** [comment]
Listo. A falta de algún detalle de estilo tenemos un buen sistema
![image](https://cloud.githubusercontent.com/assets/20515815/20719880/94ce95ce-b65d-11e6-8402-3d3cdf825626.png)

**Comment by MACEMP** [comment]
EN PRODUCTIVO NO APARECE EL FILTRO DE FECHAS
![image](https://cloud.githubusercontent.com/assets/22589031/20766023/00b2d660-b735-11e6-86c8-b0b6e984f3fd.png)
@minigoBinpar @CristianBinpar

**Comment by CristianBinpar** [comment]
Parece ser caché, a nosotros nos funciona bien.

Cerramos el issue y si se detecta un nuevo error se reabre.
