### ISSUE TITLE
PLANTILLA PRESUPUESTO : NO REFLEJA CORRECTAMENTE LAS UNIDADES PRESUPUESTADAS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#132]
![image](https://cloud.githubusercontent.com/assets/22589031/20537313/f9a4dd44-b0ec-11e6-9fb8-401f244f6689.png)
Al descargar la plantilla presupuesto, el dato Nº Unidades presupuestadas es incorrecto.
En la imagen se ve como en el producto el nº de unidades no está presupuestado y en el excel aparecen 297 unidades
El dato unidades se tomará posteriormente para calcular el importe del presupuesto por producto, de ahí la relevancia de trasladar bien este dato al excel
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
El resto de datos es correcto y sólo falla este?

**Comment by minigoBinpar** [comment]
No tiene sentido. En base de datos y en el programa responde correctamente. ¿Como se llama el campo en la consulta original en inglés?

**Comment by MACEMP** [comment]
No se trata de una consulta a la BBDD es el INFORME PLANTILLA PRESUPUESTO.
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/20672550/f80d3802-b581-11e6-93d8-ee1ec3d73f97.png)
Solucionado. Subo versión a beta y seguimos en ello
