### ISSUE TITLE
SERVICIO DE NOVEDAD: POSIBLIDAD DE DEJAR EL CAMPO SN Y FECHA VACIO 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#133]
Actualmente cuando se asigna un servicio de novedad a un producto permite la reasignación a otro servicio de novedad, pero no permite indicar sin servicio de novedad y sin fecha.
Es conveniente permitir que no aparezca asignado el producto a ningún servicio de novedad/fecha.
@CristianBinpar

**Comment by minigoBinpar** [comment]
hecho. Ahora subo
![image](https://cloud.githubusercontent.com/assets/20515815/20703908/cfc725dc-b61d-11e6-86c7-34e7df1def77.png)
