### ISSUE TITLE
ERROR MENSAJE CAMBIO DE FECHAS: ERROR EN DATO FECHA ESTIMADA PAIS DE IMPRESION

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#134]
El mensaje recibido notifica:
	
Le comunicamos que se han realizado los siguientes cambios en la sección fechas del producto Convivir con Niños y Adolescentes con Trastorno por Déficit de Atención e Hiperactividad (LIBRO):
Ha cambiado la FECHA ENTREGA MANUSCRITOS de - - - a 29/04/2016.
Ha cambiado la FECHA DE PUBLICACIÓN ESPERADA EN PAÍS DE IMPRESIÓN de - - - a 31/01/2017.
Si lo desea, visite el siguiente enlace para obtener más información:

Sin embargo, la fecha que indica como PUBLICAICON ESPERADA EN PAIS DE IMPRESIÓN corresponde a la FECHA PREVISTA ENTRADA EN DPTO EDITORIAL

![image](https://cloud.githubusercontent.com/assets/22589031/20576999/9ff64952-b1c0-11e6-865e-96c65f9350dc.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/20602943/9efdbf22-b25f-11e6-9b00-90e847331bc6.png)

Controlado. Ahora subo versión
