### ISSUE TITLE
BETA PPD: NO SE PUEDEN EDITAR LOS DESTINATARIOS DE MAIL

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#135]
![image](https://cloud.githubusercontent.com/assets/22589031/20596769/49cabcb8-b240-11e6-8a62-12ea3ff26865.png)
Al tratar de editar los destinatarios de mails en beta aparece la pantalla de error.
@CristianBinpar

**Comment by minigoBinpar** [comment]
Controlado. Subo versión en un rato y todo controlado.
