### ISSUE TITLE
COLOMBIA: SOLICITAN INCORPORAR LA VISUALIZACIÓN DE 5 DECIMALES EN PROYECTO VIABILIDAD

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#137]
Reportan la siguiente necesidad desde Colombia:
_El nuevo campo de PROYECTO DE VIABILIDAD, al ingresar el valor correspondiente a Cotización de PESO en dólares solo deja ver dos decimales, y en nuestro caso con TC a hoy  el valor seria   0,00032 y aunque hace correctamente la operación es importante ver el valor completo (en este caso solo muestra 0,00) para el momento de actualizar costos._

¿Sería posible que esta visualización con 5 decimales solo estuviese operativa para Colombia? Por el momento ninguna otra filial lo ha solicitado, y en España visualizar 5 decimales es inncesario.
@CristianBinpar

**Comment by MACEMP** [comment]
Cómo va la resolución de este caso? Colombia ya está cargando datos y necesita que aparezcan los 5 decimales 
@CristianBinpar @minigoBinpar

**Comment by MACEMP** [comment]
Desde Colombia preguntan cuando estará disponible la visualización de 5 decimales.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Ángeles, desde base de datos advierte que hacer el cambio de 2 a 5 decimiales puede suponer pérdida de datos de los campos 'importe'... ¿es asumible ?

**Comment by MACEMP** [comment]
Si la pérdida de datos supone que desaparezca la cantidad reflejada en el campo, no es asumible, pero si supone que las cantidades actuales aparecerán p.e. 53,00000 , sí que es asumible.
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Voy a hacer primero el cambio en BETA a ver que resultados nos devuelve la base de datos. Te aviso, revisamos y si es óptimo repetimos el proceso en producción

**Comment by minigoBinpar** [comment]
Listo
![image](https://cloud.githubusercontent.com/assets/20515815/21149883/596a9112-c15d-11e6-9325-4247787db7b7.png)

**Comment by MACEMP** [comment]
Fenomenal! Vaya ristra de números. Gracias.
@minigoBinpar
