### ISSUE TITLE
ERROR CAMPO AUTOR EN PDF 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#138]
![image](https://cloud.githubusercontent.com/assets/22589031/20618287/78cdac56-b2ee-11e6-9e8e-6f1f7af47d3a.png)
![image](https://cloud.githubusercontent.com/assets/22589031/20618380/ee950bb4-b2ee-11e6-9b03-b0ae10b50ed4.png)
En el PDF aparecen 2 autores, cuando uno de ellos ha sido eliminado.
En el campo AUTOR NOMBRE se ha introducido T. Gregory APELLIDO Walker
@CristianBinpar

**Comment by minigoBinpar** [comment]
Solucionado. Subo versión en breves.
![image](https://cloud.githubusercontent.com/assets/20515815/20623214/ccdbaa1a-b306-11e6-8ef5-1c3864e38902.png)

![Uploading image.png…]()
