### ISSUE TITLE
SERVICIO DE NOVEDAD: NO APARECE PRODUCTO EN EL LISTADO DE DISPONIBLES 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#139]
![image](https://cloud.githubusercontent.com/assets/22589031/20620049/fb2ec21c-b2f7-11e6-9528-070aead2209a.png)
El Voet no aparece entre los productos disponibles para asignar SERVICIO DE NOVEDAD por lo que no se le puede asignar.
El producto ya está puesto a la venta. Ver pantalla fechas
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Hola Ángeles! La nueva funcionalidad de la lista de servicio de novedad nos dice que sólo se muestran productos con el campo _Fecha de puesta a la venta real en filal_ definidos con una fecha aún no vencida.

Deduzco que hay que añadir una nueva condición de que también muestre los productos que independientemente de este campo fecha, no estén asignado a un servicio de novedad.

¿Es correcto?

**Comment by MACEMP** [comment]
Así es. En los servicios de novedad ahora incorporamos productos que ya se han puesto a la venta.
El servicio de novedad es una agrupación de productos (libro impreso) que se envía a las librerías. En muchas ocasiones ponemos a la venta los libros de forma individual y, días más tarde, los agrupamos.
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

El problema de esto es que si condicionamos por vencimiento de fecha y por servicio de novedad aun no asignado, perdemos la funcionalidad de poder elegir productos ya asignados a un servicio de novedad y reasignarlos

**Comment by MACEMP** [comment]
La posibilidad de reasignar servicio de novedad es esencial, ya que las fechas cambian constantemente por lo que  no podemos prescindir de ella.
@minigoBinpar @CristianBinpar

**Comment by MACEMP** [comment]
![image](https://cloud.githubusercontent.com/assets/22589031/20639657/bdf49aca-b3c9-11e6-88cb-e1b605cca478.png)
Este producto TRATADO DIABETES - LIBRO tiene un servicio de novedad asignado en Marzo, pero el laboratorio que lo patrocina no permite ponerlo a la venta hasta abril . El producto ya no aparece en el listado para reasignar el servicio de novedad. Esta situación no es muy frecuente, pero ocurre, por lo que la reasignación tiene que permitir gestionar casos como este.
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
El listado de productos en servicio de novedad mostrará sólo los productos no asignados a un servicio de novedad o aquellos cuya fecha de servicio de novedad no haya vencido
