### ISSUE TITLE
INFORMACIÓN DE PRODUCTO - ESTADO PRODUCTO: convertir el combo en editable

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#14]
Este sería el único campo que hemos detectado que sería conveniente que fuese editable, ya que a medida que se trabaja con el PPD, los distintos departamentos pueden sugerir incorporaciones de ESTADO DE PRODUCTO

**Comment by CristianBinpar** [comment]
Sería más conveniente que se solicite por email y se actualiza en poquisimo tiempo.
