### ISSUE TITLE
SERVICIO DE NOVEDAD: PRODUCTO ASIGNADO A UN S/N QUE NO APARECE EN LA PESTAÑA FECHAS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#140]
![image](https://cloud.githubusercontent.com/assets/22589031/20620498/5443d91c-b2fa-11e6-9617-e70d276827e4.png)
PRODUCTO: SEGG: MANUAL TERAPEUTICO EN GERIATRIA (LIBRO) FILIAL ESPAÑA COPY ESPAÑA
No aparece la fecha del servicio de novedad, a pesar de estar asignado a un servicio de novedad
@CristianBinpar

**Comment by minigoBinpar** [comment]
Listo
![image](https://cloud.githubusercontent.com/assets/20515815/20720796/dfefa112-b660-11e6-88b4-c2d68391b785.png)
