### ISSUE TITLE
ERROR AL GENERAR PDF 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#141]
![image](https://cloud.githubusercontent.com/assets/22589031/20624942/372dfcde-b310-11e6-99c9-e76d22335e7b.png)

Al generar el PDF del producto ebook de la obra DERRICKSON: FISIOLOGÍA HUMANA se obtiene el error de la imagen.
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Puedes pasarme el enlace de este producto? no soy capaz de encontrarlo por nombre ni por ID en ninguna base de datos

**Comment by MACEMP** [comment]
https://ppd.medicapanamericana.com/DerivativeWork/index?id=0e7be7a5-758d-447e-8ade-166fd7505178&e=1&m=v&scroll=mdp 
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
Listo
![Uploading image.png…]()
