### ISSUE TITLE
FECHA ESTIMADA PAIS IMPRESION: NO TOMA EL DATO EN FILIAL

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#142]
![image](https://cloud.githubusercontent.com/assets/22589031/20639130/40eaf0aa-b3bb-11e6-8197-b09bd711cdb6.png)
![image](https://cloud.githubusercontent.com/assets/22589031/20639133/57904b3e-b3bb-11e6-8672-01f18cebefad.png)
En este producto no aparece reflejado en FILIAL ESPAÑA el campo FECHA ESTIMADA que sí aparece en el PAIS COPY
@CristianBinpar

**Comment by MACEMP** [comment]
Solo aparece la fecha en la información de producto  si se incluye una fecha en la filial ¿NO sería mejor que apareciese cuando se crea por primera vez la información de filial?
![image](https://cloud.githubusercontent.com/assets/22589031/20723116/86db4924-b669-11e6-88b2-45d179efa4ba.png)
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
Listo. Cuando creamos nueva filial por primera vez busca si el filial-copy tiene fecha est. pais impr. y la copia. Y al editar cualquier filial, lo mismo.

![image](https://cloud.githubusercontent.com/assets/20515815/20744964/1ccb5a30-b6df-11e6-905f-59050ce0a90c.png)
