### ISSUE TITLE
Actualizar orden en listados en función de la prioridad de los autores

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PPD#143]

**Comment by MACEMP** [comment]
PANTALLA
![image](https://cloud.githubusercontent.com/assets/22589031/20740866/b4947bc6-b6c6-11e6-81d0-a80d6c938a13.png)
PDF
![image](https://cloud.githubusercontent.com/assets/22589031/20740678/59cdde7c-b6c5-11e6-9d45-317eb3449cde.png)
INFORME PLANIFICACION
![image](https://cloud.githubusercontent.com/assets/22589031/20740817/76c4ae74-b6c6-11e6-9c0c-ea8a58c5ef67.png)

En la visualización en pantalla aparece los autores en el orden correcto, pero en el PDF y en el INFORME PLANIFICACION sigue apareciendo el orden jerárquico preestablecido.

@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/20747091/0a4b3236-b6e9-11e6-940c-4f748d2dc870.png)

Listo
