### ISSUE TITLE
Cambios en diseño pantalla login

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PPD#144]
- [ ] Añadir logo EMP

- [ ] Evitar scroll

- [ ] Añadir copy

- [ ] Recordar usuario como label

Similar a: https://prm.medicapanamericana.com/Login

**Comment by minigoBinpar** [comment]
@MACEMP 
@CristianBinpar 

![image](https://cloud.githubusercontent.com/assets/20515815/20964128/9647f92c-bc70-11e6-93c4-a138df53985d.png)
