### ISSUE TITLE
POSIBILIDAD DE CREAR UN REPOSITORIO DENTRO DEL PPD DE DOCUMENTOS ASOCIADOS A UNA OBRA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#145]
El director editorial solicita disponer de un  repositorio de documentos asociados a una obra.
"_...cuando damos el alta de la obra, además de enviar el documento de alta, enviamos también la siguiente documentación (archivos):
	CV si es un autor nuevo.
	Proyecto de edición / Justificación.
	Índice de capítulos provisional
	Capítulos modelo (provisional)
	Evaluación del proyecto.
Si estos archivos se pudieran incluir en la ficha de la obra en el PPD seria fantástico.
Y lo mismo tendríamos que hacer con el Informe de promoción y venta, y el Power point"_ 
La idea es evitar el enviar un correo con el documento en word que elabora el dpto. editorial con la información de ALTA OBRA junto con los documentos que relaciona (CV, índice,...).
Al crear una nueva obra se podría "subir" la información a ese repositorio de información.
¿Es viable? 
@CristianBinpar @minigoBinpar

**Comment by CristianBinpar** [comment]
Nueva zona "Documentos asociados" dentro de obra.
Listado con documento y botón añadir documento que lleva a sección Drag&Drop y subida a repositorio, con estructura: Documentación/ISBN

**Comment by minigoBinpar** [comment]
Listo
![image](https://cloud.githubusercontent.com/assets/20515815/21150960/1be43e70-c161-11e6-88fd-6f4517df01ff.png)

![image](https://cloud.githubusercontent.com/assets/20515815/21151026/4aea53a8-c161-11e6-9e59-3bd43f33e38f.png)

**Comment by MACEMP** [comment]
Fenomenal! Todavía no lo veo en beta, pero tiene buena pinta
@minigoBinpar

**Comment by MACEMP** [comment]
Unicamente descarga el PDF 100 AÑOS... no el PDF subido a la obra (ALTA OBRA MARTIAÑEZ)
![image](https://cloud.githubusercontent.com/assets/22589031/21172993/960c509c-c1d5-11e6-8405-5acb632da11c.png)
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP cierro esta tarea porque ya tiene una tarea de mejora aparte en #168
