### ISSUE TITLE
MENSAJES: INCORPORAR DENOMINACIÓN SAP

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#146]
![image](https://cloud.githubusercontent.com/assets/22589031/20741024/dedf805a-b6c7-11e6-9aa1-cb3d4a77c328.png)
Incorporar en todos los mensajes el campo SAP .
Los usuarios no logran identificar rápidamente de qué producto se trata. La incorporación de una nueva línea con el campo SAP elimina cualquier duda.
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

![image](https://cloud.githubusercontent.com/assets/20515815/20965539/5cbed328-bc76-11e6-8109-99e55bf9a77d.png)

Se notifica el campo SAP al inicio de todos los mensajes a excepción de:
- Creación y modificación de autor
- Creación y modificación de obra
