### ISSUE TITLE
MEJORAR VISUALIZACION "COMENTARIOS" EN PANTALLA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#147]
![image](https://cloud.githubusercontent.com/assets/22589031/20741504/ec798c58-b6ca-11e6-92e4-d027ee870087.png)
Los comentarios solo se pueden leer completos si estamos en modo edición, en modo consulta solo se ve una línea y media del comentario y no permite el desplazamiento hacia abajo de las flechas de desplazamiento.
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Las funcionalidades de flechas y expandir el texto responden correctamente: 
![image](https://cloud.githubusercontent.com/assets/20515815/20966529/0814b8d8-bc7b-11e6-9db5-785fa0257198.png)

Por motivos de espacio y diseño originalmente vienen colapsadas para que que sature la página (que ya es de por sí la página más extensa de todo el proyecto)

![image](https://cloud.githubusercontent.com/assets/20515815/20966515/f8569f6a-bc7a-11e6-9507-6602381b0047.png)

Podemos darle un tamaño algo mayor por defecto:
![image](https://cloud.githubusercontent.com/assets/20515815/20966665/bbc008d8-bc7b-11e6-8776-7a259df20fd9.png)
