### ISSUE TITLE
MENSAJES: MEJORA LEGIBILIDAD

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#148]
![image](https://cloud.githubusercontent.com/assets/22589031/20745003/651f5d40-b6df-11e6-978c-96a8cb4dd16d.png)
Se solicita desde Editorial y Producción destacar con algún color, p.e. rojo el texto que indica
Nueva obra dentro del mail que se genera al incorporar nueva obra al PPD.

@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
![image](https://cloud.githubusercontent.com/assets/20515815/20966057/dd5e4c64-bc78-11e6-9d57-9f52f70dcff4.png)
