### ISSUE TITLE
EEROR GUARDADO DATOS : MODIFICANDO UNA FECHA PREVISTA VENTA FILIAL

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#149]
![image](https://cloud.githubusercontent.com/assets/22589031/20782895/58d8fdb4-b790-11e6-8113-ac3ba1b8de64.png)
Producto Libro
Título LORENZO: Farmacología básica....

@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP  Solucionado Ángeles.

Mil perdones pero lo he probado en producción para asegurarme y se ha difundido la notificación. Espero que no surja conflictos ni nada.

![image](https://cloud.githubusercontent.com/assets/20515815/20786490/ac0e8196-b7a6-11e6-9bac-d97ee70e79fb.png)

**Comment by MACEMP** [comment]
Comprobado! Funciona OK
@minigoBinpar @CristianBinpar
