### ISSUE TITLE
SERVICIO DE NOVEDAD: APARECEN LOS PRODUCTOS DE TODAS LAS FILIALES

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#15]
En el listado para asignar un producto a un servicio de novedad, solo tienen que aparecer los productos de la filial no los de todas las filiales. P.e. el 100 Tecnicas de Osteopatía (LIBRO) aparece 2 veces una con servicio de novedad asignado (FIlial España) y otra sin servicio de novedad asignado (Filial Venezuela). Solo tiene que aparecer el producto de la Filial.
@CristianBinpar

**Comment by minigoBinpar** [comment]
Me parece que no estoy entendido bien esta tarea @MACEMP . Internamente tiene filtros para mostrar únicamente productos de la filial del usuario en curso. ¿Deberíamos comentarlo al teléfono?

**Comment by minigoBinpar** [comment]
@MACEMP Te muestra los resultados de todas las filiales porque tu perfil es SUPERADMINISTRADOR. Un administrados ve sólo productos relativos a su filial (ya me parecía raro que se me hubiera pasado esto).
