### ISSUE TITLE
PROBLEMAS AL CREAR CONSULTAS EN EL PPD

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#151]
![image](https://cloud.githubusercontent.com/assets/22589031/21010532/da2f3042-bd4c-11e6-8e3a-80bc73dd0ab1.png)
Cuando se expande la Tabla DerivativeWorkBranches se multiplica por n el número de filas, lo que hace imposible ejecutar la consulta
@CristianBinpar

**Comment by minigoBinpar** [comment]
Dejamos programada reunión para el miércoles 14dic a las 9.00 para aclarar tema consultas y generación de tablas mediante interrelaciones de tablas
