### ISSUE TITLE
Definir con Ángeles los campos por tipo de producto

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PPD#152]
Revisar y actualizar los camops definidos por tipo de producto.

**Comment by MACEMP** [comment]
¿Cómo obtengo un listado de todos los campos por tipo de producto que hay actualmente?
@CristianBinpar @minigoBinpar

**Comment by MACEMP** [comment]
En el Excel adjunto aparecen todas las tablas y todos los campos que hay en cada tabla, con un campo ejemplo.
¿Podemos hacer la selección de campos desde este archivo?
[PPD INDICE TABLAS_CAMPOS.xlsx](https://github.com/BinPar/PPD/files/644435/PPD.INDICE.TABLAS_CAMPOS.xlsx)
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
Hola @MACEMP 

La tabla derivativework contiene, en su mayoría, todos los campos que poseen los distintos productos. Pero no existe una asociación de cada uno de ellos con respecto a dichos tipos de producto (workType).

La asociación se hace a otro nivel. Lo ideal sería montar un excel o documento con una tabla que asocie tipo de producto y campos (o que campos no deben mostrarse para x producto).

**Comment by MACEMP** [comment]
Adjunto un Excel con los campos a mostrar/no mostrar por tipo de producto
[2016 CAMPOS MOSTRAR_NO MOSTRAR POR TIPO DE PRODUCTO.xlsx](https://github.com/BinPar/PPD/files/652055/2016.CAMPOS.MOSTRAR_NO.MOSTRAR.POR.TIPO.DE.PRODUCTO.xlsx)
@CristianBinpar @minigoBinpar
