### ISSUE TITLE
VISUALIZACIÓN ORDEN AUTORES: NO SE VISUALIZA IGUAL EN EL INFO OBRA QUE EN ORDEN DE IMPORTANCIA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#154]
![image](https://cloud.githubusercontent.com/assets/22589031/21050337/686e79da-be1a-11e6-8c06-beb41b3a4ec1.png)

En la pestaña ORDEN DE IMPORTANCIA aparece correctamente el orden, sin embargo en la info de obra,  en la pantalla inicial, el Director (segundo por orden de importancia) aparece en la segunda página. 
Tendría que aparecer en segunda lugar en la página de inicio.
@CristianBinpar

**Comment by minigoBinpar** [comment]
Solucionado.
![image](https://cloud.githubusercontent.com/assets/20515815/21229255/47600896-c2e1-11e6-9b07-b2c2d41b5ec2.png)

Próxima subida.
