### ISSUE TITLE
ERROR EN MENSAJE : ###CAUSATIVE##

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#155]
Aparace ###causative### en el mensaje modificación producto

![image](https://cloud.githubusercontent.com/assets/22589031/21093232/fd043b24-c050-11e6-8054-3278ca46e593.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
No soy capaz de encontrar la obra. ¿Puedes pasarme enlace?

**Comment by MACEMP** [comment]
Este es el producto al que se refiere
https://ppd.medicapanamericana.com/DerivativeWork?id=0e7be7a5-758d-447e-8ade-166fd7505178&m=v  
DERRICKSON: FISIOLOGIA HUMANA - LIBRO

Gracias a este error podemos comprobar que la información que facilita el mensaje no es suficiente para localizar la obra/producto. Tenemos 2 obras que se titulan Fisiología Humana, que a su vez generan productos con el mismo título. Tendríamos que incorporar algún campo más al mensaje para que fuese realmente descriptivo del producto al que se refiere.
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
Listo
![image](https://cloud.githubusercontent.com/assets/20515815/21228024/86475a1e-c2dc-11e6-88bc-c4e0e67f90c6.png)

En subida de versión quedará corregido
