### ISSUE TITLE
ACTUALIZACION CONSULTAS (EXCEL PERSONALIZADO) USUARIOS PPD 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#157]
He creado la primera consulta actualizable en Excel. Funciona correctamente y muestra los campos solicitados por  el Dpto. Editorial, sin embargo a la hora de ACTUALIZAR la consulta, no llega a actualizarse porque no estos usuarios del PPD no tienen acceso a la BBDD
¿Cómo se puede resolver esta situación?
¿Crear un usuario común para que puedan actualizar las consultas?
¿Utilizar el mismo usuario del PPD, previamente autorizado por vosotros?
@CristianBinpar

**Comment by MACEMP** [comment]
![image](https://cloud.githubusercontent.com/assets/22589031/21102739/b02ff052-c07f-11e6-85a1-f3bc9815c406.png)
@minigoBinpar @CristianBinpar

**Comment by MACEMP** [comment]
Pendiente de estudio por parte de BINPAR de cuantos usuarios se van a crear con permiso para actualizar los excel que se generan de las consultas a la BBDD
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
@CristianBinpar 

Estamos hablando de unos 25-30 usuarios (o un usuario genérico para todos)

**Comment by minigoBinpar** [comment]
@MACEMP 
Te mando los datos en un email
