### ISSUE TITLE
PRECIO DEFINITIVO INTERNACIONAL: PERMITIR LA EDICIÓN DEL CAMPO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#158]
![image](https://cloud.githubusercontent.com/assets/22589031/21100603/4b258dd4-c075-11e6-886d-eef169866f7a.png)
Este campo no permite la edición, por lo que no se puede oficializar el precio establecido (no el resultado propuesto de la fórmula, que es correcto)
Solicitamos se pueda editar el campo .
También solicitamos que en los campos de precios definitivos de LIBRO ACREDITADO aparezcan 2 decimales
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Inicialmente este campo no permite edición y hereda sus datos (en libro acreditado) del precio estimado internacional de su libro homólogo x2  nunca siendo este  inferior a 120 o superior a 300.

¿Al ser editable este campo, que ocurre con este recálculo? ¿Damos prioridad a lo introducido a mano, sea el valor que sea?

**Comment by MACEMP** [comment]
Si, se dará prioridad a lo introducido a mano, sea el valor que sea.
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

El campo ya es editable:
![image](https://cloud.githubusercontent.com/assets/20515815/21346763/0ff2be80-c6a6-11e6-9f9e-33a92144b969.png)


Si se quiere emplear la funcionalidad e recalculo es necesario dejar el campo vacío o igual a 0

**Comment by MACEMP** [comment]
perfecto!

**Comment by MACEMP** [comment]
Sandra y yo lo hemos probado y no podemos editar el campo, ni dejando a 0 el resto.
Aparece el icono PROHIBIDO
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Aún no he subido versión a beta! 😱 

Si me da tiempo, subo versión 1.4 a última hora de hoy

**Comment by MACEMP** [comment]
Ahora deja modificar, pero no deja poner decimales.
Cuando editas, debería dejar meter dos decimales.
@miguelBinpar

**Comment by miguelBinpar** [comment]
He editado el comentario porque imagino que el Miguel que se quería citar era @mcastros y no yo.
Un saludo.

**Comment by MACEMP** [comment]
Envié la mención a Miguel.
Ahora deja modificar, pero no deja poner decimales.
Cuando editas, debería dejar meter dos decimales.
Solicitado en la tarea.
@miguelBinpar

**Comment by miguelBinpar** [comment]
Quizás tampoco sea @mcastros sino @minigoBinpar ... No sé, en cualquier caso entiendo que no soy el destinatario de la mención. Lo digo más que nada para que la mención surta efecto y el destinatario correcto se entere.

**Comment by minigoBinpar** [comment]
@MACEMP 

Ángeles, cierro este hilo porque la incidencia responde bien y abro uno nuevo de añadir decimales .

Y así dejamos tranquilos a todos los miguel de la oficina 😄
