### ISSUE TITLE
MENSAJE MODIFICACIÓN OBRA : ESPECIALIDAD SECUNDARIA - ERROR 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#160]
![image](https://cloud.githubusercontent.com/assets/22589031/21105177/8e337e56-c089-11e6-95a0-565508b2b8fc.png)
El usuario no modificó ningún dato dentro de la obra, sin embargo el PPD emitió un mensaje de MODIFICACIÓN OBRA describiendo modificaciones en la Especialidad secundaria cuando no se tocó ese campo.
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

La funcionalidad parece correcta. Cuando subamos versión se actualizará cualquier detalle pendiente
