### ISSUE TITLE
PRODUCTOS FORMACIÓN: NO APARECEN LOS CAMPOS DURACION MESES / HORAS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#161]
![image](https://cloud.githubusercontent.com/assets/22589031/21149326/74e01d24-c15b-11e6-8706-7f336b0b7eb2.png)
Han desaparecido los campos DURACIÓN MESES - HORAS de los productos de Formación.
Estos campos aparecían en la CARACTERÍSTICAS TÉCNICAS DE PRODUCTO.
En la imagen se puede ver como aparecen en el resumen del producto real  Experto en Traumatología Deportiva (EXPERTO) ´. Este producto se creó antes de la última actualización, cuando aparecían esos campos.
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Esto viene derivado de la tarea de ordenar campos con worktype.

Cuando organicemos quedará cerrado

**Comment by MACEMP** [comment]
Los 2 campos aparecen en el resumen, pero siguen sin aparecer las celdas para introducir los datos.
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/21766190/458b33fc-d66d-11e6-95e2-78f1734bcf1e.png)

Listo. Borrar caché si no responde.
