### ISSUE TITLE
PLANTILLA PRESUPUESTO: APARECEN ELEMENTOS ELIMINADOS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#162]
En el Excel descargado PLANTILLA PRESUPUESTO aparecen productos eliminados 
![image](https://cloud.githubusercontent.com/assets/22589031/21174277/7244b42c-c1dc-11e6-8e03-1eb61c740a19.png)
Los productos eliminados pueden aparecer en el listado, pero en ese caso debiera de aparecer el campo con  ELIMINADO TRUE/FALSE
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Listo. Si el producto está eliminado así se reflejará en la columna de estado:
![image](https://cloud.githubusercontent.com/assets/20515815/21230968/f33f17d8-c2e6-11e6-9b37-d0f2c916b433.png)
