### ISSUE TITLE
GUARDAR Y COMUNICAR: NO ENVIA MENSAJE CUANDO SE MODIFICAN ALGUNOS CAMPOS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#164]
Cuando se modifican cambios
 en PRODUCTO como:
- fechas derechos desde / hasta
- tipo de contenido
- SECRETARIA TECNICA
- Fecha venta / fecha inicio curso
- Estado del contrato
en OBRA
- Editor original
no se genera el mensaje, a pesar de pinchar en GUARDAR Y COMUNICAR.
En el resto de pestañas ha funcionado correctamente, enviando el mensaje al indicar GUARDAR Y COMUNICAR o no enviándolo si utilizaba la opción GUARDAR
@CristianBinpar

**Comment by minigoBinpar** [comment]
fechas derechos desde / hasta:
no se comunican

tipo de contenido
no se comunican

Secretaria técnica:
![image](https://cloud.githubusercontent.com/assets/20515815/21222524/8b860f9e-c2c2-11e6-9260-841d17000fe9.png)

Fecha venta / fecha inicio curso
no se comunican

Estado del contrato en OBRA
no se comunican

Editor original
Se encuentra en obra (no en producto)
![image](https://cloud.githubusercontent.com/assets/20515815/21223241/7e2f5d1a-c2c6-11e6-9b5c-c130d51da710.png)

A nivel de funcionalidad interna, la notificación no varía en función de los campos modificados. Si funciona para uno funciona para todos.

El error reside en el descontrol de campos relativos a cada producto y que alguno de los mismos no se adecua a los requisitos de programación para su notificación.

Cuando se corrijan la asociación de tipos de productos - campos, quedará solucionada esta issue
