### ISSUE TITLE
MENSAJE COMPRA MINIMA: LOS AUTORES NO APARECEN EN EL ORDEN ESTABLECIDO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#165]
![image](https://cloud.githubusercontent.com/assets/22589031/21188270/1a0f30b8-c21b-11e6-93ea-4cd5d935b1c7.png)
![image](https://cloud.githubusercontent.com/assets/22589031/21188343/5de0af6a-c21b-11e6-9fce-3e3262482956.png)
En el mensaje aparece FAGOAGA en primer lugar, cuando realmente es MACIAS la primera autora
Sugiero que aparezca solo el primer autor, en el mensaje
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP  Creo que el orden es bueno

![image](https://cloud.githubusercontent.com/assets/20515815/21230357/011d1514-c2e5-11e6-9957-
75889f264647.png)
![image](https://cloud.githubusercontent.com/assets/20515815/21230380/11b6bb5a-c2e5-11e6-880d-6489e1a00452.png)

![image](https://cloud.githubusercontent.com/assets/20515815/21230391/18c4cefa-c2e5-11e6-89dd-2eaf42250e7b.png)

En próxima subida

**Comment by MACEMP** [comment]
El orden no es el correcto.
En primer lugar tendría que aparecer la primera posición y no la tercera posición.
Para evitar que aparezca un número excesivo de autores en los mensajes ¿no podría aparecer solo la primera posición?
@minigoBinpar
