### ISSUE TITLE
INCORPORAR CAMPO NÚMERO DE EDICIÓN EN OBRA Y MANTENER TAMBIÉN EN PRODUCTO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#166]
Se solicita desde el Dpto. Editorial que se incluya el campo NUMERO DE EDICIÓN en OBRA, ya que , cuando se  cree la nueva edicion de una obra ya existente en el PPD tendrá el mismo nombre que la edición anterior y nada la diferenciará de la nueva edición.
Se solicita que los números de edición ya introducidos en producto se copien en el nuevo campo en OBRA y que cuando se introduzca en OBRA aparezca automaticamente en PRODUCTO
@CristianBinpar

**Comment by minigoBinpar** [comment]
@CristianBinpar 

Esto requiere un importador

**Comment by MACEMP** [comment]
Supone muchas horas de programación?
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP  @CristianBinpar 

Se nos van 2 o 3 horas

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/21346109/25d442ee-c6a3-11e6-8e01-3141dbd2fb0e.png)

Añadido. Cierro esta tarea y abrimos una específica para el importador

**Comment by MACEMP** [comment]
No encuentro el issue del importador ¿lo has creado?
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
No, perdona. ¿puedes crearlo tu para ver exactamente que necesitáis y poder hacer cálculos?
