### ISSUE TITLE
SECCIÓN DOCUMENTOS : mejoras solicitadas por dpto. editorial

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#168]
Se proponen las siguientes mejoras en la sección DOCUMENTOS OBRA:
- Incorporar un combo con los siguientes tipo de documentos: 
CV - PROYECTO EDICIÓN - INDICE PROVISIONAL - CAPITULO MUESTRA - EVALUACION EXTERNA - INFORME EVALUACION - INFORME PROMOCION Y VENTA - PPT - OTROS
- ZONA DOCUMENTOS siempre visible y no solo en modo EDICIÓN
-  Mostrar 2 iconos (o similar) que permitan Visualizar o Descargar 
El peso de cada documento es variable, pero suelen rondar los 300 KB por documento. Los capítulos de muestra pueden ser más pesados en función del tamaño del capítulo.
- Se mantendrá la sección DOCUMENTOS en ADMINISTRACIÓN, pero se relacionarán los nombres de los documentos de cada obra
@CristianBinpar

**Comment by oussa2727** [comment]
goodd

**Comment by minigoBinpar** [comment]
@MACEMP Listo. Subo versión en breves

![image](https://cloud.githubusercontent.com/assets/20515815/21359548/deb5a9ea-c6dc-11e6-96b5-bfd0256eeaf0.png)

![image](https://cloud.githubusercontent.com/assets/20515815/21359569/eb7a3f6a-c6dc-11e6-83d5-24b5d7fc65b6.png)

![image](https://cloud.githubusercontent.com/assets/20515815/21359580/f606f3ba-c6dc-11e6-83c6-f9d6e765cf82.png)

**Comment by MACEMP** [comment]
Funciona perfectamente. 
No están visibles los botones GUARDAR Y GUARDAR Y COMUNICAR.
Desde el dpto. editorial indican que es necesario que aparezcan.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Cierro issue porque el tema mensajes es otra tarea
