### ISSUE TITLE
PETICIÓN DPTO MARKETING: incorporar campo COMENTARIO con texto libre a la pestaña MARKETING

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#170]
Solicitan desde es dpto. de Marketing un nuevo campo COMENTARIO en el que puedan incorporar texto libre. Este campo de comentarios, tendrá que aparecer también en el PDF del producto.
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Sección marketing:

![image](https://cloud.githubusercontent.com/assets/20515815/21349039/23c52d12-c6b0-11e6-8748-3ea24958cff3.png)

PDF:

![image](https://cloud.githubusercontent.com/assets/20515815/21349015/117c930c-c6b0-11e6-8c9c-486b3a5df794.png)
