### ISSUE TITLE
PRECIOS PRODUCTOS FORMACION: CORREGIR CAMPOS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#171]
En la pestaña PRECIOS cuando se trata de productos FORMACIÓN, exceptuando los LIBROS ACREDITADOS que tienen otro precios, han de aparecer **_exclusivamente_** los siguientes campos:
- Precio estimado local en EUROS
- Precio definitivo local en EUROS
- Precio estimado internacional en DOLARES: dato a introducir manualmente, sin fórmulas
- Precio definitivo internacional en DOLARES : dato a introducir manualmente, sin fórmulas
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP , hay que ir con mucho cuidado en esta sección porque comenzamos a tener muchas variables y cambios y no quiero que ocurra como en los campos de productos.

En primer lugar, pides que estos tipos de productos reciban un trato especial en la sección de precios:

Cursos online
Programadas de actualización profesional
Experto
Academia online
Master
Programa de formación continuada

- Ahora bien, los recálculos sólo se efectúan en filial España, el resto de filiales no aplican ningún tipo de operación. ¿Es correcto?

- Si es un libro acreditado, algunos de sus campos se someten a un recálculo interno en función de los precios de su homólogo en papel. ¿Es correcto?

- Y ahora, estos tipos de productos sólo mostrarán:

Precio estimado local en EUROS
Precio definitivo local en EUROS
Precio estimado internacional en DOLARES: dato a introducir manualmente, sin fórmulas
Precio definitivo internacional en DOLARES : dato a introducir manualmente, sin fórmulas

Es decir, esta sección funciona hasta con 3 excepciones. ¿Me olvido algo?

**Comment by MACEMP** [comment]
Estoy a la espera de que Sandra me responda y confirme mi respuesta, pero en principio es esta:

1. Los recálculos se podrán efectuar en todas las filiales, ya que todas las filiales pueden generar productos de formación
2. Cierto. Los libros acreditados tienen otro sistema de precios
3. Cierto. Los productos relacionados solo necesitan mostrar estos 4 campos
@minigoBinpar

**Comment by MACEMP** [comment]
Respuesta de Sandra a mis comentarios. Sandra responde sobre mi correo:
Cada FILIAL debe poder meter el precio local (tanto estimado como definitivo) en su moneda local, por eso el campo sin fórmula y que cada uno indique su cantidad

El precio internacional (estimado y definitivo) siempre será en DÓLAR, pero tampoco puede llevar fórmula. Un campo vacío que cada filial pueda editar..

•	Si es un libro acreditado, algunos de sus campos se someten a un recálculo interno en función de los precios de su homólogo en papel. ¿Es correcto? Es correcto
•	Y ahora, estos tipos de productos sólo mostrarán:
Precio estimado local en EUROS ( o en la moneda de la filial) y se introduce manual, sin fórmulas.
Precio definitivo local en EUROS (igual)
Precio estimado internacional en DOLARES: dato a introducir manualmente, sin fórmulas - ok
Precio definitivo internacional en DOLARES : dato a introducir manualmente, sin fórmulas - ok


Esta es mi respuesta ¿es correcta?

1. Los recálculos se podrán efectuar en todas las filiales, ya que todas las filiales pueden generar productos de formación. No sé de que forma calcula los precios es resto de filiales, pero se puede hacer el recalculo en el caso de las acreditaciones y cómo luego se debe dejar editar. No veo el problema
2. Cierto. Los libros acreditados tienen otro sistema de precios
3. Cierto. Los productos relacionados solo necesitan mostrar estos 4 campos
@minigoBinpar

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/21767832/8e71da36-d676-11e6-873c-dab756e70c69.png)

Listo. Considero que habría que ver en detalle los recálculos para filiales que no son españa en otra tarea propia especificando bien los datos

**Comment by MACEMP** [comment]
¿La corrección está en Beta? ¿Cuando estará en producción? No puedo acceder a BETA. Abrí un issue comunicándolo.
@minigoBinpar

**Comment by MACEMP** [comment]
El número de issue de PPD BETA es #180
@minigoBinpar

**Comment by minigoBinpar** [comment]
Está en producción. 

Mañana retomo las que no son críticas de ppd
