### ISSUE TITLE
ERROR DE SERVIDOR EN APLICACION: espacio en disco insuficiente

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#172]
![image](https://cloud.githubusercontent.com/assets/22589031/21259531/26ef2bea-c382-11e6-8084-54618122edd4.png)
Al subir una imagen al PPD obtengo esta respuesta.
Es imposible que sea un problema de mi disco. Tiene espacio suficiente.
![image](https://cloud.githubusercontent.com/assets/22589031/21259654/a2d5b634-c382-11e6-873a-608d7b34fc68.png)

A Sandra le ocurre lo mismo que a mi.

@CristianBinpar

**Comment by minigoBinpar** [comment]
Solucionado con la conexión a Pana
