### ISSUE TITLE
¿COMO ENFOCAR ESTA CONSULTA AL PPD QUE SOLICITA MARKETING?

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#174]
Desde Marketing solicitan una consulta compleja porque aparecen campos que no existen como tales en el PPD.
Estos son los campos que no aparecen y que, si incluyo en una consulta, hace que se multipliquen los registros por 1000. 
Se trata de los campos asociados a ACCIONES MARKETING/FILIAL
¿Tiene eBook? (Si/No)
¿Tiene sitio web? (Si/No)
¿Tiene acreditado? (Si/No)
¿Vídeo? (Si/No)
¿Acuerdos? (Si/No)
¿Bloggers? (Si/No)

¿Se os ocurre cómo reflejar estos 6 datos en la consulta? El resto de campos que solicitan ya los tengo localizados y no presenta gran dificultad.
@CristianBinpar

**Comment by minigoBinpar** [comment]
Esto será cosa de llamarnos y encontrar la fórmula. ¿gotToMeeting de 10 minutos en un hueco que tengamos?

**Comment by MACEMP** [comment]
¿Cuándo te iría bien? ¿el viernes? Estos días estoy en Madrid con un poco de lío.
Todavía falta por decidir qué hacer con los usuarios que tienen excel 2010 en sus ordenadores y no pueden actualizar las consultas.
@minigoBinpar

**Comment by minigoBinpar** [comment]
Paso a gmail para ver reunión
