### ISSUE TITLE
NUEVA PANTALLA DE ACCESO AL PPD: NO SE MUESTRAN LAS IMAGENES

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#177]
Pantalla de acceso utilizando EDGE
![image](https://cloud.githubusercontent.com/assets/22589031/21465615/242b1b7e-c9ab-11e6-9423-43987fe0a2a2.png)

Pantalla de acceso utilizando CHROME
![image](https://cloud.githubusercontent.com/assets/22589031/21465608/0a04f094-c9ab-11e6-8352-863e83855540.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
Corregido
![image](https://cloud.githubusercontent.com/assets/20515815/21814292/1981e37c-d759-11e6-951a-60ece509b3c6.png)
