### ISSUE TITLE
INFORME PLANIFICACIÓN: ERROR OBTENIENDO INFORME:FAILED TO CONNECT TO SERVER

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#179]
![image](https://cloud.githubusercontent.com/assets/22589031/21585017/2fb89192-d0b8-11e6-903c-683a65c0d73e.png)
No se puede acceder al INFORME PLANIFICACION por error en conexión con el servidor.
Los informes PLANTILLA PRESUPUESTO y OBRAS PUBLICADAS no presentan problemas
@CristianBinpar

**Comment by minigoBinpar** [comment]
Sospecho que se trata de un problema de tiempos del servidor al requerir un informe con tantos resultados.

Sigo investigando

**Comment by MACEMP** [comment]
Sigue respondiendo FAIL TO CONNECTO TO SERVER.
Antes de la subida de la versión 1.4 funcionaba correctamente y el número de datos era similar.
¿Sería una solución realizar filtros previos a la visualización de datos?
@minigoBinpar

**Comment by minigoBinpar** [comment]
Solucionado :)
![image](https://cloud.githubusercontent.com/assets/20515815/21840538/56874822-d7de-11e6-8600-c664ddf536f7.png)

**Comment by MACEMP** [comment]
¿está ya en producción? Gracias
@minigoBinpar

**Comment by MACEMP** [comment]
YA FUNCIONA!!!!  GRACIAS
La primera vez que lo probé no conectó y ahora acaba de responder. Estupendo!!
@minigoBinpar
