### ISSUE TITLE
BETA PPD: NO SE PUEDE ACCEDER A ESTE SITIO WEB

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#180]
![image](https://cloud.githubusercontent.com/assets/22589031/21600530/25c59df8-d17e-11e6-9cf2-356854de684c.png)
No puedo acceder a beta
@CristianBinpar

**Comment by minigoBinpar** [comment]
Vale, ha sido algo muy raro. He tenido que cambiar el protocolo https de beta y ahora operamos con http.

http://betappd.medicapanamericana.com/

Es una beta así que con que funcione para nosotros debería bastar pero en cualquier caso seguiré consultando con el responsable de sistemas a ver que ha ocurrido
