### ISSUE TITLE
MODIFICAR ROTULO: 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#181]
![image](https://cloud.githubusercontent.com/assets/22589031/21602275/8a1b36aa-d192-11e6-88e2-e2cf2fd7807f.png)
El rótulo del campo debiera de referirse a PRODUCTO y no a OBRA.
Nueva descripción: Tipo de producto
@CristianBinpar

**Comment by minigoBinpar** [comment]
Listo
![image](https://cloud.githubusercontent.com/assets/20515815/21813603/2043e4e6-d757-11e6-8539-90778a0a4860.png)
