### ISSUE TITLE
EBOOK CREADO CON NÚMERO DE VOLUMEN: NO SE PUEDE MODIFICAR

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#182]
![image](https://cloud.githubusercontent.com/assets/22589031/21758966/c87aa036-d640-11e6-9f72-758a9c884f0f.png)

![image](https://cloud.githubusercontent.com/assets/22589031/21758910/508e8812-d640-11e6-92b2-
3ed3214a8f44.png)

Producto: Medicina familiar y ambulatorio ebook
En la primera imagen se ve el Volumen 2 del ebook y en la segunda los campos de ebook entre los que no se encuentra Volumen.
No se puede eliminar el número de volumen del ebook porque no aparece el campo Volumen en la información del ebook.
Teniendo en cuenta que el ebook se crea a partir del producto libro, que sí puede tener varios volúmenes ¿Cómo se puede borrar ese campo?

En este caso lo haremos borrando el producto ebook y creándolo nuevamente.
@CristianBinpar

**Comment by minigoBinpar** [comment]
He añadido el campo a la edición de libro electrónico
![image](https://cloud.githubusercontent.com/assets/20515815/21814104/835baee6-d758-11e6-85fa-a303f6a16b16.png)

Subo versión y queda disponible
