### ISSUE TITLE
PPD ACTUALIZACIÓN CONSULTA EXCEL: EL USUARIO NO TENÍA AUTORIZACIÓN

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#183]
![acceder bbdd ppd](https://cloud.githubusercontent.com/assets/22589031/21763173/d014d804-d65c-11e6-9be7-a68d8b696537.jpg)
Hemos comprobado que los usuarios que utilizan Excel 2016 SI pueden acceder a las actualizaciones del PPD conectado con el servidor, sin embargo hay un error en la autorización.
Los datos de acceso que han utiliizado son:
usuario: ppd_readonly
pass: Ppd_R34d0nly

@CristianBinpar

**Comment by minigoBinpar** [comment]
Vale, ha sido algo muy raro. He tenido que cambiar el protocolo https de beta y ahora operamos con http.

http://betappd.medicapanamericana.com/

Es una beta así que con que funcione para nosotros debería bastar pero en cualquier caso seguiré consultando con el responsable de sistemas a ver que ha ocurrido
