### ISSUE TITLE
PRODUCTO EBOOK: LOS CAMPOS DE FECHA INICIO/FIN CURSO NO TIENEN QUE APARECER

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#184]
![image](https://cloud.githubusercontent.com/assets/22589031/21766417/b18271be-d66e-11e6-9cf2-9c2bddfbc029.png)
![image](https://cloud.githubusercontent.com/assets/22589031/21766445/ee55e77e-d66e-11e6-964d-56761e78be84.png)
Los campos FECHAS CURSO no tienen que aparecer en el producto EBOOK
@CristianBinpar

**Comment by MACEMP** [comment]
También aparecen estos campos en productos LIBRO
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
Con #163 quedaría solucionado
