### ISSUE TITLE
ERROR PRECIOS FORMACIÓN: CAMPO ESTIMADO INTERNACIONAL NO ES EDITABLE_ELIMINAR NOTAS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#185]
![error precio int formacion](https://cloud.githubusercontent.com/assets/22589031/21809725/39912df4-d749-11e6-968d-53bf5da8dbe0.png)
Sandra comunica el siguiente error en la carga de precios de productos de formación:
_Error precios formación  en campo estimado internacional. NO es editable y todas estas notas deben eliminarse. solo valen para acreditados. Gracias_
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

No entiendo muy bien cual es el problema Ángeles o.O

**Comment by MACEMP** [comment]
Parece que el problema de la NO EDICION del campo Precio Estimado Internacional ya está resuelto.
El otro problema que indica Sandra consiste en que aparecen las notas relativas a los cálculos de los libros acreditados.
En los casos en los que no hay cálculos, no debiera de aparecer el mensaje de advertencia.
@minigoBinpar

**Comment by minigoBinpar** [comment]
Entendido. Todo correcto entonces:
![image](https://cloud.githubusercontent.com/assets/20515815/21816569/d6d6e916-d760-11e6-9e78-c96046e9f438.png)
