### ISSUE TITLE
EL PRODUCTO "AUTOEVALUACION" HA DE TENER LOS MISMOS PRECIOS QUE EL RESTO DE PRODUCTOS DE FORMACIÓN

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#186]
![precios autoevaluacion](https://cloud.githubusercontent.com/assets/22589031/21810277/6a69d3ca-d74b-11e6-92b1-ece821d80885.png)
Los campos de precios de este tipo de productos son los de FORMACIÓN no los de LIBROS o EBOOK
@CristianBinpar

**Comment by minigoBinpar** [comment]
No figura en la lista de productos de:
![image](https://cloud.githubusercontent.com/assets/20515815/21815490/146e7630-d75d-11e6-9184-3d1233fea55e.png)

Añadido:
![image](https://cloud.githubusercontent.com/assets/20515815/21815585/8ab98d84-d75d-11e6-8e8c-13afd06e70d0.png)

**Comment by MACEMP** [comment]
Cierto, pero una vez que empezaron a cargar los datos de este producto se han dado cuenta de que los precios son los de formación.
Disculpas por no haberlo incluido en el listado.
@minigoBinpar

**Comment by minigoBinpar** [comment]
Sin problemas. En la próxima subida queda corregido
