### ISSUE TITLE
Gestión de productos de formación

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PPD#2]

**Comment by minigoBinpar** [comment]
@MACEMP 

¿Podrías concretarme algo más esta tarea?

**Comment by MACEMP** [comment]
@minigoBinpar @minigoBinpar 
en el archivo FUNCIONALIDADES PPD V2.0, aparece una pestaña con los campos que deben de mostrar los Productos de formación. 
![image](https://cloud.githubusercontent.com/assets/22589031/19230857/107f83da-8ed7-11e6-94bc-6b5a2e717158.png)

**Comment by MACEMP** [comment]
@minigoBinpar @CristianBinpar 
En este módulo de Formación también se incorporan los PROGRAMAS DE ACTUALIZACION de Argentina.
En el Excel hay una pestaña con el detalle de los campos a incorporar.
![image](https://cloud.githubusercontent.com/assets/22589031/19231256/5c8ac7b0-8ed9-11e6-9444-412a4ae69193.png)

**Comment by minigoBinpar** [comment]
@MACEMP 

Para el nuevo tipo de producto de PROGRAMAS DE ACTUALIZACIÓN, ¿podrías ponerme un ejemplo de la información que van a contener los nuevos campos?. Números, textos, campos de si/no...

**Comment by MACEMP** [comment]
![image](https://cloud.githubusercontent.com/assets/22589031/19378382/7e0e1994-91ec-11e6-82f2-4c9626afce5e.png)
En el Excel con las funcionalidades, hay una columna que indica si ya está el campo en el ppd v1.1. Si ya está ese campo, no hay que hacer nada.
Si aparece NO en la columna, te detallo el tipo de información
en la imagen adjunta.
En el caso de Acreditado, es un campo que debiera mostrar un desplegable con las Universidades/sociedades acreditadoras y debiera de poder ser editable, ya que el número de entidades acreditadoras se irá incrementando y modificando.
Este campo de Acreditado también se aplica a CURSOS /EXPERTOS / MASTER / LIBRO ACREDITADO
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

¿En que sección de FILIAL situamos Universidad Principal y Universidad Secundaria?

**Comment by MACEMP** [comment]
Sería conveniente crear una nueva pestaña de filial específica para los productos de formación. Es posible que algún otro campo tenga que ir a esa pestaña.
Te indicaré cuales cuando lo confirme con Elena.
