### ISSUE TITLE
SERVICIO DE NOVEDAD: DENOMINACION SAP + EAN EN EL DESPLEGABLE Añadir producto a nuevo servicio de novedad

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#21]
Para facilitar la búsqueda del producto, debiera de aparecer en el desplegable, el campo DENOMINACIÓN SAP & EAN. 
Actualmente aparece el Título del producto (largo) + tipo producto. Si se modifica a DENOMINACIÓN SAP también aparece el autor y de qué tomo se trata, asimismo facilita la información de tipo de producto ya que en la denominación SAP también queda reflejado si es libro/libro acreditado/ebook/programa/sitio web/master.

**Comment by minigoBinpar** [comment]
@MACEMP 

Estamos hablando de sustituir los campos existentes por SAP y EAN o aádir a lo ya existente¿

**Comment by MACEMP** [comment]
@minigoBinpar 
Añadir a lo existente
