### ISSUE TITLE
NO ACTUALIZA LA FECHA DE PUBLICACIÓN REAL EN UNA FILIAL NO COPY

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#22]
Siento decirte que cuando actualizo un copy de otra filial, una vez elimino la fecha de publicación real y actualizo la fecha estimada (en datos de filial del copy de la obra), no refresca el dato en la filial España
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Creo que funciona bien, pero no termino de entender que quieres decir en el mensaje. ¿Puedes volver a explicarmelo?

Gracias

**Comment by MACEMP** [comment]
Ahora funciona correctamente, y la FECHA REAL PUBLICACION EN PAIS DE IMPRESIÓN se copia automaticamente en el resto de filiales ¡bien!
Lo que no está correcto es la etiqueta de FECHA PAIS DE IMPRESIÓN en la pantalla de datos de producto, porque la fecha que toma es la de FECHA ESTIMADA PAIS IMPRESIÓN. Si se mantiene esa fecha, habría que añadir al título de la columna FECHA ESTIMADA PAIS IMPRESIÓN. Tal y como está ahora no se sabe si es la real o la estimada.
Home Obras Afecciones Medicoquirúrgicas para Fisioterapeutas Afecciones Medicoquirúrgicas para Fisioterapeutas (LIBRO ACREDITADO) Información de filial España
![image](https://cloud.githubusercontent.com/assets/22589031/20057673/1b6397a6-a4ed-11e6-8ea0-3bb551c0e3a1.png)
@minigoBinpar

**Comment by minigoBinpar** [comment]
Hecho entonces.

Muestro en subida versión
