### ISSUE TITLE
LOS PRODUCTOS ELIMINADOS NO DEBEN DE APARECER EN LOS LISTADO 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#23]
Los productos eliminados no debieran de aparecer en los listados, sea en pantalla o en excel. Si tienen que aparecer tendrían que tener un indicador de PRODUCTO ELIMINADO o similar.
PRODUCTO Terapeutica médica en urgencias.
![image](https://cloud.githubusercontent.com/assets/22589031/19262156/cada2df2-8f95-11e6-9be9-3f4d8aabd158.png)
Aparecen 2 libros electrónicos, uno de ellos eliminado.
![image](https://cloud.githubusercontent.com/assets/22589031/19262135/a871fb32-8f95-11e6-9d5c-46830c132dfe.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
¿De qué listados quieres que los elimine?
