### ISSUE TITLE
REASIGNAR SERVICIO DE NOVEDAD: PRODUCTOS PUBLICADOS EN OTRA FILIAL

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#25]
Antecedente:
para facilitar la reasignación de un producto a un servicio de novedad, se decidió que no apareciesen los productos PUBLICADOS en el listado.
Problema detectado
El estado PUBLICADO no está asociado a una filial sino al producto, por lo tanto, cuando un producto está    PUBLICADO en una filial, ya no aparece disponible en otra filial para asignarle servicio de novedad.
POSIBLE SOLUCION:
los productos publicados tienen que aparecer en el listado de servicio de novedad. Lo deseable es que tuviesen algún tipo de indicación sobre su estado PUBLICADO - FILIAL. P.e. Gerencia Hospitalaria COPY COLOMBIA. Estado Publicado. En Colombia a la venta. En España y resto de filiales pendiente de ser recibido y puesto a la venta.
@CristianBinpar

**Comment by MACEMP** [comment]
En el listado de productos a incorporar en el servicio de novedad de una filial, aparecerán aquellos que no tengan FECHA DE PUESTA A LA VENTA REAL EN FILIAL, a pesar de haber sido PUBLICADOS en el país de COPY.
![image](https://cloud.githubusercontent.com/assets/22589031/19926275/f0cccae6-a0f3-11e6-9c3d-73e14d6201d4.png)
@minigoBinpar

**Comment by CristianBinpar** [comment]
Totalmente de acuerdo @MACEMP.

Modificamos la consulta.

**Comment by minigoBinpar** [comment]
Hecho. Ahora para mostrar resultados la fecha de puesta a la venta real en filial tiene que ser mayor que la fecha actual. Sino se entiende que el plazo ya pasó y no se puede añadir a un servicio de novedad.
