### ISSUE TITLE
INCORPORAR CAMPOS FECHAS DEPARTAMENTO EDITORIAL

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#26]
Añadir los siguientes campos de fecha:
- FECHA ENTREGA MANUSCRITOS
- FECHA PREVISTA ENTRADA EN DEPARTAMENTO EDITORIAL
- FECHA REAL ENTRADA EN DEPARTAMENTO EDITORIAL
  Estas incorporaciones se comunicaron en un correo antes de ponerse en marcha el GITHUB.
  @CristianBinpar

**Comment by MACEMP** [comment]
La v1.3 debiera de incorporar estos 3 campos nuevos de fechas ya que están muy relacionados con los productos de formación. 
Las fechas se incorporan en el bloque FECHAS
@minigoBinpar @CristianBinpar

**Comment by MACEMP** [comment]
Es importante incorporar estas 3 fechas a la versión 1.3
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

¿qué perfil recibirá notificación cuando se realicen cambios en estos 3 nuevos campo-fechas?
