### ISSUE TITLE
EXCEL DESCARGABLE CON TODOS LOS CAMPOS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#27]
¿Sería posible generar YA un INFORME EXCEL SIN FILTROS y SIN PRESENTACIÓN EN PANTALLA que incorporase todos los campos ?
@CristianBinpar

**Comment by CristianBinpar** [comment]
Se sustituirá por la formación a Ángeles para habilitar acceso directo a BBDD desde excel.
