### ISSUE TITLE
GENERAR NUEVO MENSAJE DE NOTIFICACIÓN A OTRAS FILIALES DE 2 FECHAS CLAVE

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#28]
El nuevo mensaje tendrá como destinatarios usuarios de otras filiales.
Se emitirá cuando se produzca la introducción/modificación de 2 campos de fecha:
- Fecha estimada en país de impresión
- Fecha real en país de impresión
  Cuando se modifican el resto de fechas NO se genera este mensaje.
  El texto es similar al de cualquier otra comunicación de modificación de fechas.
  @CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

¿qué perfiles serán destinatarios de este email? ¿Administradores de las otras filiales?

**Comment by MACEMP** [comment]
Si, en principio serán los administradores de las filiales.
@minigoBinpar

**Comment by MACEMP** [comment]
No veo este mensaje en el Administrador mails. El mensaje con título CAMBIO EN LAS FECHAS se refiere al mensaje ya existente que genera cuando se modifica cualquier fecha.
![image](https://cloud.githubusercontent.com/assets/22589031/20137271/c9dd7b70-a679-11e6-949f-b6fa225a550e.png)
![image](https://cloud.githubusercontent.com/assets/22589031/20137284/d6390420-a679-11e6-8bab-a4176043acfc.png)
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
Correcto. No es un mensaje típico sino que, para acortar el desarrollo en tiempo y recursos, se envía de forma automática a las otras filiales
