### ISSUE TITLE
USUARIO ELIMINADO SIGUE RECIBIENDO MENSAJES

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#29]
![image](https://cloud.githubusercontent.com/assets/22589031/19378703/6caa8528-91ee-11e6-8cc5-75d545d5284e.png)
Este usuario SANDRITA se creó para realizar pruebas y ya se ha eliminado, sin embargo sigue recibiendo los mails ya que tiene asociado un perfil. Lo mismo sucede con el usuario MAC angelescastrof@gmail.com
Los usuarios eliminados no debieran de recibir ningún mail.
@CristianBinpar

**Comment by MACEMP** [comment]
Los usuarios eliminados siguen recibiendo los mensajes.

**Comment by MACEMP** [comment]
Otro ejemplo que ilustra el error 
![image](https://cloud.githubusercontent.com/assets/22589031/19519793/afbf3818-960d-11e6-9327-c04de8355645.png)
Este destinatario no debiera de aparecer como destinatario.
@minigoBinpar

**Comment by MACEMP** [comment]
Siguen apareciendo los usuarios eliminados como destinatarios de correos.

**Comment by minigoBinpar** [comment]
@MACEMP 

¿Es posible que siga enviando mensajes a este usuario por que su perfil está seleccionado en la sección de administración de emails?

**Comment by MACEMP** [comment]
RESUELTO. SE OBVIARÁN LOS USUARIOS ELIMINADOS
CASO RESUELTO
@minigoBinpar @CristianBinpar
