### ISSUE TITLE
Eureka: Campo de ponderación

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PPD#3]

**Comment by minigoBinpar** [comment]
@MACEMP ,

¿Podrías concretarme algo más esta tarea? ¿Dónde se situaría este nuevo campo? ¿Extrae sus datos de alguna otra sección? ¿Contiene alguna consideración más a tener en cuenta?

**Comment by MACEMP** [comment]
Este campo puede añadirse a la pestaña RELEVANCIA Y PRESUPUESTO DE VENTAS
Los valores serán numéricos, siendo el valor mínimo 1 y el máximo 100
Este campo, en el futuro, con seguridad se incorporará al INFORME PLANTILLA PRESUPUESTO
Ya aparece este campo en el PDF PRODUCTO

**Comment by MACEMP** [comment]
@minigoBinpar 
no logro ver el campo ni en beta ni en producción
¿está ya subida la versión?
