### ISSUE TITLE
CORRECCIÓN COMBO TIPO DE OBRA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#30]
Modificar los siguientes tipos de obra (REALMENTE ES TIPO DE PRODUCTO):
- Expertos universitarios pasa a EXPERTO UNIVERSITARIO
- Masters universitarios pasa a MÁSTER UNIVERSITARIO
- Eliminar del combo PHARMA
@CristianBinpar

**Comment by MACEMP** [comment]
CORRECCIÓN DE LA TAREA ANTERIOR
Estas son las denominaciones correctas de los productos de formación que hay que corregir en el combo.
![image](https://cloud.githubusercontent.com/assets/22589031/19448944/17c5c5d2-94a4-11e6-82ff-1cf1817014f4.png)
Se mantiene la petición de eliminar PHARMA del combo

**Comment by minigoBinpar** [comment]
- Autoevaluaciones es nuevo o sustituye a alguno

- Si borramos pharma, tendremos conflicto con los productos pharma ya creados. Habría que sustituirlos en base de datos por otros

**Comment by MACEMP** [comment]
1. Autoevaluaciones es nuevo
2. No hay productos Pharma creados. No creará conflicto. Desconocemos el motivo por el que aparece ese producto, parece que es una herencia del pasado remoto del PPD.
