### ISSUE TITLE
RECEPCIÓN DUPLICADA DE MAILS 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#33]
Estamos recibiendo duplicados los mails de modificaciones.
¿Será porque las Secretarias técnicas tienen ahora 2 tipos de perfil y envía desde los dos?
![image](https://cloud.githubusercontent.com/assets/22589031/19514268/36285c42-95f3-11e6-86f9-5bc522238578.png)
En la imagen se ve que a la misma hora envía 2 mensajes iguales . En estos casos EMERGENCIAS EN ANESTESIOLOGÍA y BANCO DE OVULOS.
Hemos recibido más de 5 mails duplicados, todos modificados por una secretaria técnica  que tienen los 2 perfiles.

**Comment by minigoBinpar** [comment]
Creo que queda controlado. Cuando actualicemos versión se verá. En cualquier caso si un usuario tiene dos o más perfiles y estos están asignados a dicha accion en la sección de gestión de emails recibirá emails duplicados
