### ISSUE TITLE
MENSAJE EXTRAÑO AL ELIMINAR EL EAN INDICA :  EAN: 9988498351033 => China**

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#36]
De: PPDtecnicalSuport [mailto:emailppdinfo@gmail.com] 
Enviado el: miércoles, 19 de octubre de 2016 18:06
Para: PRUEBA CREACION USUARIO USU ESPAÑA prmv2colombia@gmail.com; Miriam Abbas Gonzalez mabbas@medicapanamericana.es; Verónica Álvarez Núñez valvarez@medicapanamericana.es; Belén Sánchez bsanchez@medicapanamericana.es; Rosana Martín Martín rmartin@medicapanamericana.es; Mac Cas angelescastrof@gmail.com; Marce Diaz mdiaz@medicapanamericana.es; SANDRITA ZF sandritazf@hotmail.com; Ana Otero Garcia aotero@medicapanamericana.es; Jaime Miguel Díaz Hernández jdiaz@medicapanamericana.es; Blanca Sanchez blsanchez@medicapanamericana.es; Ester Duque Rodríguez eduque@medicapanamericana.es; Belén Sánchez bsanchez@medicapanamericana.es; Paulina Aceves paceves@medicapanamericana.es; ZENIA RAMIREZ GONZALEZ zramirez@medicapanamericana.es; Helga Santiago hsantiago@medicapanamericana.es; Álex Nieto anieto@medicapanamericana.es; Beatriz Ruiz Palacios bruiz@medicapanamericana.es; Rocío Martínez Jiménez rmartinez@medicapanamericana.es; Ana Otero Garcia aotero@medicapanamericana.es; Carmen Triguero ctriguero@medicapanamericana.es; Ana Arribas aarribas@medicapanamericana.es; Beatriz Ruiz Palacios bruiz@medicapanamericana.es; Manoli Ruiz mruiz@medicapanamericana.es; Carlos Gómez cgomez@medicapanamericana.es; Elisa Lucas Fernández elucas@medicapanamericana.es; Àngel Pérez i Pérez aperez@medicapanamericana.es; Alicia Pizarro apizarro@medicapanamericana.es; Emilio Mosquera Vázquez emosquera@medicapanamericana.es; Azahara Arribas de Benito azarribas@medicapanamericana.es; Jose Rico jrico@medicapanamericana.es; Manoli Ruiz mruiz@medicapanamericana.es; Álvaro Pintos Pena apintos@medicapanamericana.es; José Carlos Cabrero Cobo jccabrero@medicapanamericana.es; prueba angeles angelescastrofer@live.com; JULIA DOMÍNGUEZ BRAVO jdominguez@medicapanamericana.es; Daniel Moreno Laso dmoreno@medicapanamericana.es; Juan Caso jcaso@medicapanamericana.es; Elena Feduchi efeduchi@medicapanamericana.es; Yolanda Espinosa Oliva yespinosa@medicapanamericana.es; Rosa Martinez Casas rosa.martinez@medicapanamericana.es; Cristina Concha Reimundez cconcha@medicapanamericana.es; MANUEL MARIA JULBEZ CAMPOS mjulbez@medicapanamericana.es; Noemí Martín Pérez nmartin@medicapanamericana.es; Helga Santiago hsantiago@medicapanamericana.es; Rosana Martín Martín rmartin@medicapanamericana.es; Marcos Íñigo: minigo@binpar.com; Sandra Zarapuz Fernández szarapuz@medicapanamericana.es; Ángeles Castro macastro@medicapanamericana.es; Paco Cotrina fjcotrina@medicapanamericana.es
Asunto: PPD: Modificación de producto en el PPD

PANAMERICANA 

Panamericana 

Se ha modificado el producto Guía esencial de Metodología en Ventilación Mecánica no Invasiva (LIBRO ACREDITADO) en el Plan de Publicaciones Dinámico.
El usuario Ángeles Castro ha realizado las siguientes modificaciones:
**# Description: => NO EXISTE EL LIBRO ACREDITADO EN ESTA OBRA
EAN: 9988498351033 => China**
Si lo desea, visite el siguiente enlace para obtener más información:
Pulse aquí para ver información disponible 

@CristianBinpar

**Comment by MACEMP** [comment]
@minigoBinpar @CristianBinpar 
Otro mensaje extraño relacionado con CHINA
![image](https://cloud.githubusercontent.com/assets/22589031/19549606/82e3372a-96a5-11e6-8bb5-8c682e712fdd.png)

**Comment by MACEMP** [comment]
Por lo que veo, este error no se corregirá en la v1.3.
Me escriben usuarios que reciben el mensaje
![image](https://cloud.githubusercontent.com/assets/22589031/20004159/fa9ab126-a28a-11e6-8482-557dcfb5c311.png)
y que encuentran incomprensible esta parte del mensaje ==> China
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
hecho. proxima subida
