### ISSUE TITLE
ERROR GUARDADO DATOS EN PRODUCCION

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#37]
![image](https://cloud.githubusercontent.com/assets/22589031/19549189/30af9efa-96a3-11e6-8e94-53da9c784b58.png)
error en guarda datos
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Ya desactivé el correo, se puede seguir trabajando sobre PPD.

Quedo a la espera de que me comuniques con Jose o me pases los datos del nuevo email de envío.

**Comment by MACEMP** [comment]
@minigoBinpar @CristianBinpar 
estoy esperando que Jose me llame para explicarle.
