### ISSUE TITLE
V1.3  PESTAÑA UNIVERSIDAD : INCORPORAR CUADRO RESUMEN FILIAL/UNIVERSIDAD ACREDITADORA/PAIS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#41]
Incorporar un cuadro resumen de las universidades acreditadoras de otras filiales, del mismo producto:
![image](https://cloud.githubusercontent.com/assets/22589031/19566362/445e945a-96ea-11e6-95a3-4732164a8e5d.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
Listo:
![image](https://cloud.githubusercontent.com/assets/20515815/20522456/b636d56c-b0b0-11e6-80ed-3c7071296a27.png)
