### ISSUE TITLE
V1.3 PRODUCTO MASTER: NO APARECE DATOS FORMACION

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#43]
![image](https://cloud.githubusercontent.com/assets/22589031/19566900/377650d2-96ec-11e6-9857-40f7ca4190e0.png)

Al acceder a la página de datos del producto no aparece el apartado FORMACIÓN.
@CristianBinpar

**Comment by minigoBinpar** [comment]
Creo que esta incidencia guarda relación con la organización de productos y secciones a mostrar
