### ISSUE TITLE
PROYECTO VIABILIDAD: GENERACION PDF y EXCEL

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#47]
La pestaña PROYECTO VIABILIDAD (costes) ha de mostrar 2 botones que permitan generar PDF / EXCEL del producto con los siguientes campos:
Copy - Filial - Obra - Tipo Producto - EAN - AUTORIA - TITULO -  DENOMINACION SAP y tabla que aparece en la pantalla
La misma información deberá descargarse en EXCEL

**Comment by MACEMP** [comment]
También deberá de totalizar las filas y columnas, tanto en el EXCEL como en el PDF.
@CristianBinpar @minigoBinpar

**Comment by MACEMP** [comment]
En la información del PROYECTO VIABILIDAD se han de mostrar las fechas:
FECHA PUBLICACIÓN INICIAL
FECHA PREVISTA PAíS DE IMPRESIÓN
@minigoBinpar

**Comment by MACEMP** [comment]
**PDF**: el pdf descargado es poco legible, ya que las columnas y filas están desordenadas.
**SUMATORIO COLUMNAS**: al no descargar el excel por producto, hay que incorporar un sumatorio por cada una de las columnas existentes de modo que se refleje también en el PDF.
Al acceder al producto se verá el total coste del producto tanto en pantalla como en el pdf
Ejemplo de PDF descargado y visualización en pantalla
![image](https://cloud.githubusercontent.com/assets/22589031/19699192/a25ecd84-9af2-11e6-85f9-3e8f8d92e3f2.png)

**DESPLAZAMIENTO POR LOS CAMPOS** : resulta complicado moverse por las fechas ya que, el calendario oculta la fecha en ocasiones la fecha inferior.

@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP  
Última fila añadida. aparecerá en la próxima subida. 
Como comentamos por teléfono, los estilos no están aún incluidos. Es simplemente saber que los datos aparecen bien

**Comment by MACEMP** [comment]
De acuerdo. Pendiente de revisar hasta que se suba la nueva versión y se incluyan los estilos.
RECORDATORIO DE CAMPOS QUE HAN DE APARECER EN EL PDF (ver más arriba): Copy - Filial - Obra - Tipo Producto - EAN - AUTORIA - TITULO - DENOMINACION SAP  FECHA PUBLICACION INICIAL - FECHA PREVISTA PAIS DE IMPRESIÓN - PAIS DE IMPRESIÓN y tabla que aparece en la pantalla 
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Ángeles, toda la información que solicitas aparece en el encabezado del pdf. te lo adjunto. La gente de estilos vendrá a darle una pasada porque ahora mismo el diseño es muy justo

[100.T.CNICAS.DE.OSTEOPATIA.PROGRAMA.DE.FORMACION.CONTINUADA.Espa.a..pdf](https://github.com/BinPar/PPD/files/575103/100.T.CNICAS.DE.OSTEOPATIA.PROGRAMA.DE.FORMACION.CONTINUADA.Espa.a.pdf)

**Comment by MACEMP** [comment]
Con seguridad el departamento financiero solicitará que se incluya, al menos, el campo DENOMINACION SAP, ya que el de AUTORIA ocuparía mucho mas espacio 

@minigoBinpar

**Comment by minigoBinpar** [comment]
SAP está incluido (pero me aprece que el pdf de ejemplo tiene el campo vacío)

Autoría está (pruebasBinpar4 pruebasBinpar4), pero solo incluyo un autor (el primero según la clasificación de importancia dónde revisor es el más puntuado) porque añadir todos los autores podría acabar siendo un poco locura

**Comment by MACEMP** [comment]
He incorporado un nuevo campo SAP (si que estaba), pero sigue sin aparecer en el PDF, al menos en el que yo descargo
![image](https://cloud.githubusercontent.com/assets/22589031/20058290/81c05d6a-a4f0-11e6-81bb-bdd3a43a52ed.png)
@minigoBinpar

**Comment by minigoBinpar** [comment]
Correcto, pero es que aún no he subido versión 😱

**Comment by MACEMP** [comment]
![image](https://cloud.githubusercontent.com/assets/22589031/20058665/602682cc-a4f2-11e6-9209-59bfe2ad3bf8.png)
En las celdas no aparece el símbolo de la moneda ¿Aparecerá en la subida de versión? ;-)

@minigoBinpar
