### ISSUE TITLE
CREAR PERFIL FINANCIERO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#48]
Crear un nuevo perfil de usuario FINANCIERO
Con acceso y edición de todos los campos.
@CristianBinpar

**Comment by MACEMP** [comment]
HE enviado 2 invitaciones al usuario cgomez@medicapanamericana.es en BETA PPD con perfil FINANCIERO, pero no ha recibido ninguna invitación, a pesar de que el mensaje indica que se ha enviado correctamente.
![image](https://cloud.githubusercontent.com/assets/22589031/19734963/ee74cf86-9ba9-11e6-8369-6d86c57a2b33.png)
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/19762943/4fb43f42-9c3c-11e6-82c9-7fc7a84a79cd.png)

@MACEMP  beta me responde bien. vuelve a probar por si fuera algo puntual
