### ISSUE TITLE
FECHA ESTIMADA PAIS DE IMPRESION: EL DATO NO APARECE REFLEJADO EN TODAS LAS FILIALES

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#49]
Si el país copy introduce el dato FECHA ESTIMADA PAIS DE IMPRESIÓN, este dato, debiera  de aparecer en  el mismo campo del resto de filiales y no es así. Las filiales nocopy no pueden modificar esa fecha por lo que aparece en blanco
![image](https://cloud.githubusercontent.com/assets/22589031/19604233/ac20da9c-97b4-11e6-818e-7bf89e4d74ab.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP ¿Cuando puede una nocopy establecer su FECHA ESTIMADA PAIS DE IMPRESIÓN?

**Comment by MACEMP** [comment]
La FECHA ESTIMADA PAIS DE IMPRESIÓN la establece el PAIS COPY por eso es necesario que se copie y refleje en los datos del resto de filiales
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Ángeles,

La solución a este problema son dos pasos:

1. Cada vez que añadimos FECHA ESTIMADA PAIS DE IMPRESION a una filial copy, el resto de filiales del mismo producto obtienen el mismo valor en el mismo campo. Esto soluciona la futura creación de fechas.

2. He creado un miniprograma que recorre toda la base de datos y copia la FECHA ESTIMADA PAIS DE IMPRESION de la filial copy a sus filiales hermanas. He hecho la prueba en beta y todo parece correcto. Si pudieras revisar que los datos se han copiado bien y no hay nada fuera de lugar o algún producto con la fecha mal, cuando tu digas paso el programa en producción y listo.

**Comment by MACEMP** [comment]
Al introducir el dato de FECHA ESTIMADA PAIS DE IMPRESION en el país COPY SIGUE SIN REFLEJARLO en la filial ESPAÑA
![image](https://cloud.githubusercontent.com/assets/22589031/19692067/cbbce07e-9ad6-11e6-93ca-10ac76e4e4af.png)
![image](https://cloud.githubusercontent.com/assets/22589031/19692103/ee3aae56-9ad6-11e6-9537-2a2b8290e9e7.png)
@minigoBinpar

**Comment by MACEMP** [comment]
Sigo haciendo pruebas en beta y no aparece en las filiales cuando el país copy introduce el dato
@minigoBinpar

**Comment by minigoBinpar** [comment]
Perdona Ángeles, no actualicé versión para verificar el punto 1. Ahora mismo lo hago
 Sobre el punto 2, ¿has podido testear algo?
