### ISSUE TITLE
listado novedades: cambiar en columna productos TITULO DE LA OBRA por DENOMINACIÓN SAP

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#51]
MUCHAS GRACIAS
@CristianBinpar

**Comment by MACEMP** [comment]
ESTA MISMA MODIFICACION SE APLICA AL LISTADO QUE APARECE PARA CREAR NUEVO SERVICIO DE NOVEDAD
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Modificado. Subo en breves y listo.
