### ISSUE TITLE
PLANTILLA PRESUPUESTO: TOMA DE FORMA ERRONEA EL CAMPO Nº UNIDADES

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#52]
El campo Nº Unidades del Excel que se descarga, tiene que reflejar el nº de Unidades del campo PRESUPUESTO VENTAS, sin embargo no es así y trae un dato que no sé de dónde sale.
P.e. MILLER - LIBRO ELECTRONICO tiene 0 unidades en el Presupuesto ventas, sin embargo aparecen 497 en el Excel
Ver imágenes

![image](https://cloud.githubusercontent.com/assets/22589031/19713597/a3f1d934-9b47-11e6-9341-3f601118129a.png)
![image](https://cloud.githubusercontent.com/assets/22589031/19713654/0e0899f2-9b48-11e6-9cbc-186b53191efe.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
¿de qué excel estamos hablando?

**Comment by MACEMP** [comment]
El Excel PLANTILLA PRESUPUESTO

**Comment by minigoBinpar** [comment]
@MACEMP 
Porque este campo es un sumatorio de todas las unidades. aunque un producto flilial tenga 0, si sus hermanos producto filial tienen unidades definidas se aplica el sumatorio.

Cambio para que sea individual y todo listo
