### ISSUE TITLE
MAILS NOTIFICACION FECHAS : SE RECIBE DOS VECES EL MISMO MAIL

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#56]
Se reciben los mails de modificación de fechas, duplicados:
![image](https://cloud.githubusercontent.com/assets/22589031/19772303/0f4314f4-9c66-11e6-89ad-43c1c0da1875.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
Cuando actualicemos version produccion se soluciona

**Comment by MACEMP** [comment]
OK!

**Comment by MACEMP** [comment]
Sigue el mismo problema: envía duplicado el mail de notificación cambio fechas.
Usuario que realizó la modificación: Ana Otero que tiene 2 perfiles -Secretaria técnica y Producción
¿será ese el motivo?
![image](https://cloud.githubusercontent.com/assets/22589031/20213423/f3b6b9e4-a808-11e6-970f-7cc22125edd3.png)
![image](https://cloud.githubusercontent.com/assets/22589031/20213446/0516e5e2-a809-11e6-9145-f50404236a35.png)
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
Correcto. Todo apunta a que ese es el motivo
