### ISSUE TITLE
INCLUIR DENOMINACION SAP EN LAS NOTIFICACIONES DE MODIFICACION PRODUCTO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#57]
Hemos detectado que, al incluir en el mensaje unicamente la Denominación del producto y entre paréntesis el tipo de producto, no queda claro de qué producto se habla especialmente cuando se trata de productos con varios tomos .
El campo DENOMINACION SAP aporta toda la información en solo 40 caracteres.

![image](https://cloud.githubusercontent.com/assets/22589031/19801676/85a64b30-9d00-11e6-9ae1-4aaeb9c2cb4e.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
hecho. proxima subida
