### ISSUE TITLE
MODIFICACION CAMPO DERECHOS: NO ENVÍA MENSAJE DE NOTIFICACION

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#58]
No emite mensaje cuando se modifican los campos relativos a DERECHOS. Los campos están en el apartado INFORMACIÓN  PRODUCTO, que SI envía mensajes cuando se modifican otros campos.

![image](https://cloud.githubusercontent.com/assets/22589031/19803628/f4cb4048-9d09-11e6-8437-50857834ccd9.png)

@CristianBinpar

**Comment by MACEMP** [comment]
Ahora envía un mensaje indicando DESCRIPTIONINFO: CHINA, pero no cuando se introducen los datos de DERECHOS en todos los productos. El envío del mail al modificar el campo derechos es errático.
![image](https://cloud.githubusercontent.com/assets/22589031/19806131/07929bae-9d19-11e6-9036-f90d29ea1c02.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
hecho. próxima subida lo verás
