### ISSUE TITLE
FORMATO CAMPO EAN QUE SE DESCARGA EN INFORME PLANIFICACION y PLANTILLA PRESUPUESTO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#59]
El formato del campo EAN que se descarga en estos dos informes es distinto y dificilmente solucionable en Excel, por lo que, cuando se intenta hacer un cruce de datos entre ambos informes no es posible ya que al no tener el mismo formato, no se puede establecer la relación.
Solución: cuando se descarga cualquier informe, el campo EAN ha de ser NUMÉRICO sin decimales y sin separadores de miles
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

![image](https://cloud.githubusercontent.com/assets/20515815/20052033/47ee80b2-a4d2-11e6-8f54-018b8d6dfe0b.png)

Ambos informes muestran un campo EAN igual. Podrás verlo cuando suba versión (en breves).

¿Te es correcto este formato para trabajar?

**Comment by MACEMP** [comment]
Si, siempre que cuando se descargue a excel tenga siempre el mismo formato.

**Comment by minigoBinpar** [comment]
hecho pues. en breves subo versión
