### ISSUE TITLE
NO APARECEN LOS DATOS DE PRODUCTOS FORMACIÓN en RESUMEN INFORMACIÓN FILIAL

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#60]
No aparecen los datos de FILIAL cuando se trata de productos de formación.
En la imagen aparecen los campos de donde toman los datos. Los que no tienen nota, es que son autoexplictativos
![image](https://cloud.githubusercontent.com/assets/22589031/19853311/b2c7cdb8-9f68-11e6-8a0f-c1d33a3fdd22.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/19980119/1f6bcbfe-a1fd-11e6-9755-c44f1b659f27.png)

solucionado
