### ISSUE TITLE
INCORPORAR A HOME ACCESOS : DATOS FORMACIÓN - PROYECTO VIABILIDAD

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#61]
Hay que incorporar a la  HOME los vínculos a estas nuevas pestañas 
@CristianBinpar

**Comment by minigoBinpar** [comment]
Completado

**Comment by MACEMP** [comment]
@minigoBinpar 
Falta el acceso a DATOS FORMACIÓN, o por lo menos en mi pantalla se queda en VIABILIDAD
![image](https://cloud.githubusercontent.com/assets/22589031/19976027/6df73c7c-a1ee-11e6-9815-f1f5cc7104f7.png)
