### ISSUE TITLE
ERROR GUARDADO DATOS: CREANDO UN AUTOR

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#62]
![image](https://cloud.githubusercontent.com/assets/22589031/19974571/3505d32e-a1e9-11e6-9c24-ffe95cae6d19.png)
Al querer GUARDAR los datos de un nuevo autor, sale el mensaje: ERROR GUARDADO DATOS
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Control + R??

He probado a crear y todo parece funcionar correctamente. Dale otro intento a ver

**Comment by MACEMP** [comment]
Hago ctrl+R y misma respuesta.
¿Puede ser que el autor seleccionado (Marian de Castro)  al tener una dirección de mail entre en conflicto con algo??
@minigoBinpar @CristianBinpar

**Comment by MACEMP** [comment]
@minigoBinpar @CristianBinpar 
El error se produce cuando selecciono un autor del listado que propone. Si introduzco los datos de un nuevo autor no da problemas.

**Comment by minigoBinpar** [comment]
@MACEMP osea que no es CREANDO UN AUTOR sino EDITANDO

**Comment by MACEMP** [comment]
Si, es tomando un autor ya creado

**Comment by minigoBinpar** [comment]
Dime que usuario y campos varías porque me responde bien

**Comment by MACEMP** [comment]
Tomo al autor MARIAN DE CASTRO o LOPEZ RUIZ o cualquiera de los que aparecen cuando tecleas en la caja de búsqueda autor.
Seguro que ese es el problema ¿no será que ese listado de autores está en otra ubicación y no lo encuentra?
@minigoBinpar

**Comment by minigoBinpar** [comment]
pero la caja de búsqueda sólo aparece en CREANDO AUTOR, 

?????

**Comment by minigoBinpar** [comment]
vale, ya lo tengo controlado.

Solucionado en la próxima subida de versión

**Comment by MACEMP** [comment]
OK!
@minigoBinpar
