### ISSUE TITLE
ERROR MENOR EN DELETREO: ACTUALIZADA- SECCIÓN UNIVERSIDAD 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#63]
El mensaje de confirmación tiene un error de deletreo
![image](https://cloud.githubusercontent.com/assets/22589031/19974974/9eb4f63c-a1ea-11e6-9b5b-33e77ac6cea3.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
Corregido (visible en próxima verisón)
