### ISSUE TITLE
ZONA FECHAS: NO APARECE EL CALENDARIO EN VARIAS FECHAS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#64]
![image](https://cloud.githubusercontent.com/assets/22589031/19975464/5a901b7e-a1ec-11e6-98fd-296e3cc0a1e0.png)

No puedo incorporar las fechas marcadas en amarillo. Al situar el ratón en el campo, no aparece el cursor ni tampoco el calendario para seleccionar la fecha.

Aparece dos veces el botón GUARDAR.
@CristianBinpar

**Comment by minigoBinpar** [comment]
solucionado

**Comment by MACEMP** [comment]
@minigoBinpar 
![image](https://cloud.githubusercontent.com/assets/22589031/19979176/d5f6623e-a1f9-11e6-9b4b-02af89b98cb7.png)
Sigo sin poder introducir datos en algunos campos y aparecen todavía 2 botones de GUARDAR.

**Comment by minigoBinpar** [comment]
Como en todas las demás issues, cuando suba versión se verán los cambios
