### ISSUE TITLE
PDF : PROYECTO VIABILIDAD

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#65]
![image](https://cloud.githubusercontent.com/assets/22589031/19975745/6c1bfb78-a1ed-11e6-8f5d-4e0c4cce66a5.png)
Al descargar el PDF del PROYECTO VIABILIDAD no aparece a qué producto se refiere. Debiera, al menos indicar EAN-AUTOR-TITULO-TIPO PRODUCTO 
@CristianBinpar

**Comment by minigoBinpar** [comment]
corregido, próxima subida
