### ISSUE TITLE
RESUMEN DATOS FILIAL: NO APARECEN LOS DATOS UNIVERSIDAD ACREDITADORA y otros

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#66]
![image](https://cloud.githubusercontent.com/assets/22589031/19976148/e396a9a4-a1ee-11e6-8081-81e414c4fa30.png)
No aparecen los datos rodeados en rojo (uni acreditadora, créditos, duración, horas)
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
solucionado.
