### ISSUE TITLE
COHERENCIA EN LA DENOMINACIÓN TIPOS DE PRODUCTOS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#67]
Por coherencia, creo que en el desplegable TIPO DE PRODUCTO, debieran de aparecer siempre en SINGULAR. Hay algunos productos que aparecen en plural y otros en singular:
Libro / Libro electrónico / Curso online
Mientras que otros aparecen en plural: Autolevaluaciones, Expertos, Libros acreditados, Másters... Éstos debieran de estar también en singular. 
Autoevaluación
Experto
Libro acreditado
Máster
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
solucionado
