### ISSUE TITLE
NO APARECEN LOS DATOS DE FILIAL CREADOS 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#68]
@minigoBinpar 

PRODUCTO: Bases del diagnóstico en Hematología (MASTER) 
No aparecen los datos de FILIAL creados.
![image](https://cloud.githubusercontent.com/assets/22589031/19979251/15725ac6-a1fa-11e6-99c1-4a85443f43c5.png)

Se puede ver que han sido creados los datos de varias filiales porque en el selector solo aparece VENEZUELA , que es la única que no creé con datos filial
![image](https://cloud.githubusercontent.com/assets/22589031/19979349/6909176a-a1fa-11e6-9f2c-b4f49b210256.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/19979953/8f60fe44-a1fc-11e6-87a6-cbc9210a2ac4.png)

solucionado. proxima subida :)
