### ISSUE TITLE
BETA PPD V1.3 NO GUARDA NUEVO PRODUCTO - EL BOTON SE "ENGRISECE"

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#69]
@minigoBinpar 
![image](https://cloud.githubusercontent.com/assets/22589031/20003358/4888925e-a286-11e6-805c-bf86fe8f4d2f.png)

No puedo GUARDAR un nuevo producto . Lo único que detecto es que el campo AÑO EDICIÓN está en amarillo, pero el dato introducido es correcto. Lo he modificado y sigue en amarillo.
Como no guarda el nuevo producto no puedo realizar todas los pasos de creación de un producto.
ESTA ES LA OBRA EN LA QUE CREO EL NUEVO PRODUCTO.
Le informamos de que se ha incorporado un nuevo participante a la obra NUEVA OBRA PRUEBA V1.3 :
MARIAN DE CASTRO (Miembro del Comité Editorial )
Si lo desea, visite el siguiente enlace para obtener más información:
Pulse aquí para ver información disponible 

Cambios realizados por Ángeles Castro (macastro@medicapanamericana.es) 

@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

¿que tipo de producto era?

**Comment by MACEMP** [comment]
Era un programa de actualización

**Comment by minigoBinpar** [comment]
Me funciona correctamente en beta.  

Prueba otra vez porque si el botón de guardar se "engrisece" quiere decir que algún campo obligatorio (remarcados en rojo) no está completo

**Comment by MACEMP** [comment]
Lo probé varias veces y el único que estaba resaltado era el año de edición 2017, que era correcto, pero no había forma de que apareciese como correcto. El resto de campos estaban OK, pero ese aparecía con el fondo amarillo, ni siquiera con los bordes en rojo. Un misterio
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Misterio. Acabo de crear uno con todos los campos y parece responder bien.

¿Puedes revisar?

**Comment by minigoBinpar** [comment]
Pd. lo de  el año de edición está bien. responde así

**Comment by MACEMP** [comment]
Revisado.
Funciona el botón de GUARDAR en las distintas pantallas
