### ISSUE TITLE
PPD PRO: MENSAJE MODIFICACIÓN EN UN CAMPO OBRA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#70]
Al modificar en el PPD el Subtítulo de la obra, se recibe un mensaje comunicando un cambio en las Especialidades secundarias. El campo Especialidades secundarias no se modificó, unicamente se corrigió el subtítulo
![image](https://cloud.githubusercontent.com/assets/22589031/20004704/2cf7022a-a28e-11e6-904d-b3166bb38dee.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
solucionado. proxima subida de version esta
