### ISSUE TITLE
MODIFICAR LOS DATOS DE SECRETARIA TECNICA DUPLICADA: MANUEL BEJAR

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#72]
He detectado que Manuel Béjar aparece como SECRETARIA TECNICA con 2 denominaciones y 2 emails distintos. No siendo ninguna de las combinaciones correcta.
![image](https://cloud.githubusercontent.com/assets/22589031/20036433/949d1a06-a408-11e6-90dd-ed455836b0e9.png)
EN PPD Beta he tratado de "arreglar" esta duplicidad, pero hay un problema y es que no permite modificar el mail de la denominación correcta porque ya existe un usuario con ese mail, a pesar de que lo he eliminado previamente.
![image](https://cloud.githubusercontent.com/assets/22589031/20036473/7c87d540-a409-11e6-965a-475f832e2f25.png)

Los datos correctos son: España Externo Manuel Béjar mail:  mbejar@siosigrafico.com .
En el PPD PRO no lo puedo modificar por lo que comento más arriba.
Por otra parte, en el PPD PRO hay 15 productos que tienen asignado a Manuel Béjar (sin España Externo) como SECTEC ¿Sería posible modificarlo en la BBDD una vez que se haya eliminado la SECTEC Manuel Bejar, en lugar de hacerlo en cada producto para evitar la generación de mails? 
Esto lo descubrí al hacer una consulta (realmente la primera que me funcionó)
![image](https://cloud.githubusercontent.com/assets/22589031/20036490/f5324f16-a409-11e6-8ced-2c3ecee0e60c.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Ángeles, Manuel Bejar tiene asociados 19 productos y ESPAÑA  EXTERNO -  MANUEL BEJAR tiene 20. 
Fusiono ambos resultados en un único España Externo Manuel Béjar mail: mbejar@siosigrafico.com, es correcto?

**Comment by MACEMP** [comment]
Efectivamente. Solo ha de aparecer el que indicas.

**Comment by minigoBinpar** [comment]
@MACEMP 

Ok. En pro debería aparecer ya de forma correcta

**Comment by MACEMP** [comment]
Perfecto! Ya aparece correctamente
@minigoBinpar
