### ISSUE TITLE
PETICION DIRECCION EDITORIAL: INCORPORAR CAMPOS PÁGINAS E INTERIOR A PRODUCTO EBOOK

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#73]
A petición de la Dirección Editorial se solicita incorporar los campos PÁGINAS e INTERIOR al apartado CARACTERÍSTICAS TÉCNICAS DEL PRODUCTO de los EBOOK. 
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Ángeles, no termino de ver el sentido en añadir número de páginas a un ebook (varía según tamaño vista dispositivo) o el interior (¿¿¿???)

**Comment by MACEMP** [comment]
Puede resultar extraño.
Realmente lo que solicitan es el número de páginas que tiene el libro en papel.
Lo ideal es que copiase el dato del campo.
Casualmente hoy me ha pedido el responsable de Eureka que le facilite el número de páginas de los libros 
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Ok. Me pongo con ello

**Comment by minigoBinpar** [comment]
Listo
![image](https://cloud.githubusercontent.com/assets/20515815/20701380/00c7d506-b613-11e6-9f4f-582370fc7d51.png)
