### ISSUE TITLE
¿Reducción nombres?

### ISSUE THREAD

**Issue by minigoBinpar** [BinPar/PPD#76]
@MACEMP 

¿Sería posible reducir los nombres de las pestañas en la sección Filial?
![image](https://cloud.githubusercontent.com/assets/20515815/20062034/7a80b722-a502-11e6-83f6-8536981e6f43.png)

¿Quizás por algo más conciso o genérico para que los estilos queden mejor en dispositivos con menor tamaño de pantalla?

**Comment by MACEMP** [comment]
Relevancia y Presupuestos de ventas= Relevancia & PPTO
Fechas y Servicio de Novedad = Fechas
El resto creo que no se puede acortar
@minigoBinpar

**Comment by minigoBinpar** [comment]
![Uploading image.png…]()
