### ISSUE TITLE
PPD V1.3 ¿entrará hoy 7/11/2016 en PRODUCCION?

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#77]
@CristianBinpar

**Comment by minigoBinpar** [comment]
Por mi, creo que sí

**Comment by minigoBinpar** [comment]
@MACEMP 
Subí versión a beta. Nos quedaría ultimar los estilos PDF de proyecto de Viabilidad. 

A menos que encuentres algún mal funcionamiento muy grave, por mi subidos

**Comment by MACEMP** [comment]
Por parte OK.
Solo encuentro algo realmente extraño: hay 2 botones GUARDAR en la zona de Fechas.
Al principio pensé que era un error de visualización, pero he descubierto que cada botón sirve para guardar fechas diferentes: el primer botón guarda las fechas que no tienen que ver con editorial y el 2º botón guarda las 3 últimas fecha añadidas. ¿Va a quedar así?
![image](https://cloud.githubusercontent.com/assets/22589031/20064004/6bc05312-a509-11e6-8458-a4129f4c3e94.png)
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Esto tiene su origen en que las nuevas fechas eran un grupo independiente para un sólo sector (comercial?). Si te parece puedo unir ambos o meterlos en unos recuadros o algo así porque es cierto que queda un poco raro el resultado final

Lo que tu digas :)

**Comment by MACEMP** [comment]
La idea del recuadro me parece muy buena. Así se diferencian y queda claro a qué se refiere cada botón GUARDAR.
La única pega es que las 3 últimas están ligadas a Editorial y, durante el proceso se producen antes que las fechas que ya existen.  Tal y cómo aparecen ahora parece que son posteriores.
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
¿Entonces recueadramos pero el intercambiamos posiciones en los blques de fechas para que tengan sentido?

**Comment by MACEMP** [comment]
Por mi si.
Por cierto a las 18:00 tengo sesión PPD con LATAM para presentar las últimas novedades de la v1.3 :-)

**Comment by minigoBinpar** [comment]
enseñarás beta o pro?

**Comment by MACEMP** [comment]
Seguramente BETA.
La fijé para hoy porque pensaba que estaría en PRO el día 3. Hoy estarán Argentina y México y mañana a la misma hora Colombia
