### ISSUE TITLE
ERROR EN CALCULO SUMA GESTION DE EJEMPLARES

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#78]
![image](https://cloud.githubusercontent.com/assets/22589031/20068614/91a8fa42-a519-11e6-91c3-c8c81dd4849a.png)
No realiza correctamente la suma
@CristianBinpar

**Comment by minigoBinpar** [comment]
Ya me cuadra el balance. Era un colateral de los días en que cada filial podía editar sus propias compras mínimas en lugar de hacerlo la filial copy.

![image](https://cloud.githubusercontent.com/assets/20515815/20098111/6564236e-a5b2-11e6-9d3c-883ca741d581.png)

En la próxima subida lo tienes.

**Comment by MACEMP** [comment]
¿puede una filial gestionar sus compras mínimas? Pensaba que solo era el país copy.

**Comment by minigoBinpar** [comment]
antiguamente. Pero se cambió para que solo pudiera filial copy
