### ISSUE TITLE
MENSAJE EXTRAÑO COMUNICACIÓN MODIFICACION PORTADA: ####CAUSATIVE####

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#79]
![image](https://cloud.githubusercontent.com/assets/22589031/20088904/a2d6e38c-a583-11e6-9086-20f526605f10.png)
Al modificar una portada en beta, se recibe el mensaje con la notificación, pero indica: 
####CAUSATIVE####
@CristianBinpar

**Comment by minigoBinpar** [comment]
Controlado. Termino con el resto de incidencias y subo versión.

**Comment by MACEMP** [comment]
Sigue apareciendo ####CAUSATIVE#### en el mail

![image](https://cloud.githubusercontent.com/assets/22589031/20168289/8b6f82c2-a721-11e6-8756-03780b616b0a.png)
@minigoBinpar

**Comment by minigoBinpar** [comment]
creo que no subí versión. al final del día de hoy subo todo

**Comment by MACEMP** [comment]
Sigue apareciendo el mensaje con CAUSATIVE
![image](https://cloud.githubusercontent.com/assets/22589031/20357943/4162d194-ac2a-11e6-886c-aa6470ebd92d.png)
@minigoBinpar

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/20516555/4562a8c0-b097-11e6-992c-a0f2d1b983c2.png)

Controlado. Subo versión
