### ISSUE TITLE
CORREGIR PALABRA MAL DELETREADA EN EL MENSAJE COPIAS PATROCINADOR

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#80]
![image](https://cloud.githubusercontent.com/assets/22589031/20089032/6d929d6e-a584-11e6-9b9d-b2d00bfb7c24.png)
La palabra LABORATORIO está mal deletreada. En lugar de LABORATORIO indicar PATROCINADOR
@CristianBinpar

**Comment by minigoBinpar** [comment]
Controlado. Termino con el resto de incidencias y subo versión.
