### ISSUE TITLE
PRODUCTO LIBRO ELECTRONICO PATROCINADO: NO APARECEN LOS DATOS DEL PATROCINADOR

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#81]
![image](https://cloud.githubusercontent.com/assets/22589031/20090820/bc3b366e-a58f-11e6-8780-48afae8a6c13.png)

Acaba de surgir un caso real en el que un patrocinador no adquiere ejemplares impresos, si no libros electrónicos. En este caso, la sección EJEMPLARES PATROCINADOS, debiera de aparecer, pero como desaparece por ser un ebook no se puede incorporar esa información, salvo en Notas del producto.
¿Podría aparecer únicamente la sección EJEMPLARES PATROCINADOS o bien toda la sección, pero sombreada la parte de GESTÓN EJEMPLARES y COMPRA MÍNIMA?
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

es decir, que aunque sea un libro electrónico quieres que aparezca la sección de gestión de ejemplares pero sólo la parte de listado de patrocinadores?

![image](https://cloud.githubusercontent.com/assets/20515815/20095005/f5872518-a5a3-11e6-89e8-932848262251.png)

**Comment by minigoBinpar** [comment]
Solucionado. Subo a beta y pro y lo tienes
![image](https://cloud.githubusercontent.com/assets/20515815/20098383/c968c94a-a5b3-11e6-8e3d-e69789e28758.png)
