### ISSUE TITLE
CAMPOS EAN- ISSN - EDICION - TOMO DESAPARECIERON DEL PPD

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#82]
![image](https://cloud.githubusercontent.com/assets/22589031/20093114/a5b621c2-a59b-11e6-8aea-a02113e0afab.png)
Con la nueva versión han desaparecido esos campos
@CristianBinpar

**Comment by minigoBinpar** [comment]
No entiendo muy bien @MACEMP 

![image](https://cloud.githubusercontent.com/assets/20515815/20095263/154eac4e-a5a5-11e6-856c-2839df1320ea.png)

**Comment by MACEMP** [comment]
Ni a Sandra ni a mi nos aparecen los campos de EAN- EDICIÓN-.... Cuando se carga la página, aparecen, pero inmediatamente desaparecen y solo se visualiza esto:
![image](https://cloud.githubusercontent.com/assets/22589031/20096625/08b0d308-a5ab-11e6-8015-354c0ff7817e.png)
@minigoBinpar

**Comment by minigoBinpar** [comment]
https://ppd.medicapanamericana.com/DerivativeWork/index?id=8cdd99a1-8fb6-48f8-a121-d2e6e4c8631e&e=1&m=v&scroll=mdp

**Comment by MACEMP** [comment]
https://ppd.medicapanamericana.com/DerivativeWork/index?id=8cdd99a1-8fb6-48f8-a121-d2e6e4c8631e&e=1&m=v&scroll=mdp 
@minigoBinpar

**Comment by MACEMP** [comment]
![image](https://cloud.githubusercontent.com/assets/22589031/20097121/2b44ba40-a5ad-11e6-9965-1970e4629e9a.png)
@minigoBinpar

**Comment by MACEMP** [comment]
Hemos detectado que ahora aparece en rojo la url y una advertencia
![image](https://cloud.githubusercontent.com/assets/22589031/20105635/9f23415a-a5d2-11e6-8d3c-fbb659029827.png) 
¿tendrá algo que ver?
@minigoBinpar
