### ISSUE TITLE
USUARIO SANDRA ZARAPUZ NO PUEDE ACCEDER A LOS MENUS DESDE LA HOME

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#83]
Sandra no puede acceder a los distintos apartados de CONSULTA/EDICIÓN desde la HOME. Solo puede acceder o bien desde el PDF en pantalla o desde el producto/datos filial
No tiene respuesta de ningún tipo cuando pincha en los distintos apartados
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

A mi me responde bien. ¿Que  dispositivo y navegador usa? ¿Control+R?

**Comment by MACEMP** [comment]
google chrome con la misma versión que yo.
Reinició, hizo CTRL + R, actualizó y nada. Sigue sin poder acceder desde los enlaces de la HOME
@minigoBinpar

**Comment by minigoBinpar** [comment]
¿Tu puedes acceder con normalidad?

Tiene que ser algo relativo a  su dispositivo.

No me lo explico sino

**Comment by MACEMP** [comment]
Accedo con normalidad, por eso le dije que revisásemos el navegador y reiniciase. Es realmente extraño. 
Desde el PDF sí que accede. Es realmente extraño

**Comment by minigoBinpar** [comment]
Qué pruebe a entrar con otro usuario (por si acaso) pero es que sospecho que es cosa del equipo.

Ya me dirás

**Comment by MACEMP** [comment]
Ya lo he comprobado y a Paco le funciona correctamente. Hablaré nuevamente con Sandra. Es raro, raro

**Comment by MACEMP** [comment]
Misterio resuelto: al actualizar versión del navegador, bloqueó las ventanas emergentes. CLOSED
@minigoBinpar @CristianBinpar
