### ISSUE TITLE
V1.3 ERROR MENSAJE ASIGNACION TAREAS MARKETING 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#84]
![image](https://cloud.githubusercontent.com/assets/22589031/20094329/0c3c0d80-a5a1-11e6-9562-6ea6438e689c.png)
Esta comunicación de tareas es errónea, ya que lo que realicé fue una "desasignación" de tareas y no una asignación.
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Me responde bien. ¿Se te repite más veces este error?

**Comment by MACEMP** [comment]
¿Qué mensaje envía cuando pasas de SI  a NO una tarea de marketing?
@minigoBinpar

**Comment by minigoBinpar** [comment]
Ninguno
