### ISSUE TITLE
ELIMINAR : PHARMA COMO TIPO DE PRODUCTO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#86]
![image](https://cloud.githubusercontent.com/assets/22589031/20102802/b51441ae-a5c7-11e6-864b-cc0663e057bc.png)
Eliminar Pharma.
Curiosamente en beta ya no aparece en el combo la opción PHARMA, tal y como se había solicitado, sin embargo en PRO si que aparece
@CristianBinpar

**Comment by minigoBinpar** [comment]
solucionado :)
