### ISSUE TITLE
ERROR DESCARGA INFORMES: SOLO DESCARGA (y se visualizan)PRODUCTOS PUBLICADOS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#87]
![image](https://cloud.githubusercontent.com/assets/22589031/20112445/b2cc6a96-a5ec-11e6-84d0-930324f7eda6.png)
Tanto en el informe PLANIFICACIÓN como el informe PLANTILLA PRESUPUESTO aparecen UNICAMENTE las obras PUBLICADAS. Tanto en el Excel como en pantalla, en el caso de PLANIFICACIÓN
Tenemos que preparar los presupuestos y es esencial que aparezcan todos los productos
@CristianBinpar 
@minigoBinpar

**Comment by minigoBinpar** [comment]
Solucionado. Termino la otra incidencia y subo versión :)
