### ISSUE TITLE
PPD BETA: CAMPOS EAN- ISSN - EDICION - TOMO DESAPARECIERON DEL PPD 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#88]
Ahora donde no aparecen estos campos es en Beta
![image](https://cloud.githubusercontent.com/assets/22589031/20112652/7f147634-a5ed-11e6-816f-74e667163bd2.png)
@CristianBinpar

**Comment by MACEMP** [comment]
Siguen sin aparecer los campos en PPD BETA
![image](https://cloud.githubusercontent.com/assets/22589031/20338750/3c386b26-abd9-11e6-9a09-58e5ccb6f359.png)
@minigoBinpar @cr

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/20352321/1d4983f6-ac17-11e6-92ea-62f89eceebd6.png)

Confirmame que tu tmb puedes verlo y cerramos issue

**Comment by MACEMP** [comment]
Confirmado. Lo veo.
@minigoBinpar @CristianBinpar
