### ISSUE TITLE
CAMPO FECHA PREVISTA PAIS DE IMPRESIÓN NO APARECE EN LA INFO DE PRODUCTO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#89]
![image](https://cloud.githubusercontent.com/assets/22589031/20144193/23537fca-a69c-11e6-83b8-69c65fee7053.png)

![image](https://cloud.githubusercontent.com/assets/22589031/20144141/f3f32c12-a69b-11e6-93dd-fceb6727496f.png)
En la sección FECHAS, aparece correctamente reflejada la fecha REAL PUBLICACION PAIS DE IMPRESIÓN, pero no aparece la fecha ESTIMADA PAIS DE IMPRESIÓN, por lo que no se refleja en el resumen de datos de FILIAL en la pantalla de info del producto. Estas dos fechas, que introduce únicamente el país de copy, deben de aparecer en las fechas del resto de filiales, y tambien debe de aparecer en el resumen de producto.
@CristianBinpar

**Comment by MACEMP** [comment]
Sigue sin aparecer la información
![image](https://cloud.githubusercontent.com/assets/22589031/20278235/2d7ac894-aaa4-11e6-8b4c-fe00f41378ce.png)
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
puedes pasarme nombre de producto donde ocurra esto?

**Comment by MACEMP** [comment]
El de la imagen de arriba sirve MANUAL PARA TECINCO SUPERIOR... LIBRO
@minigoBinpar

**Comment by minigoBinpar** [comment]
Vale, creo haber controlado los tres estados:

Si copy cambia la fecha, las demás filiales también.
Si creo una filial con una fecha en copy establecida, esta nueva hereda dicha dehca
Retroactividad para los casos ya creados de copy con fecha y fiales sin
