### ISSUE TITLE
MENSAJE MODIFICACION PORTADA: NO INDICA CUAL HA SIDO LA MODIFICACIÓN

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#9]
cuando se modifica una portada, se recibe el siguiente mensaje: 

### _Se ha modificado el producto Abordajes en Cirugía Ortopédica (LIBRO) en el Plan de Publicaciones Dinámico.
El usuario Sandra Zarapuz Fernández ha realizado las siguientes modificaciones:
Si lo desea, visite el siguiente enlace para obtener más información:
Pulse aquí para ver información disponible_ 

NO indica que se ha modificado la portada

**Comment by minigoBinpar** [comment]
Solucionado. Manda un email notificando el cambio
