### ISSUE TITLE
CAMPO DESCRIPCION DATOS PRINCIPALES DE LA OBRA: ¿CUANTOS CARACTERES ADMITE

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#90]
![image](https://cloud.githubusercontent.com/assets/22589031/20146613/e7443548-a6a4-11e6-9e02-c4624873d274.png)
La visualización del campo DESCRIPCION hace pensar que admite pocos caracteres.
¿Y campo notas del mismo apartado?
Estamos buscando un campo en el que introducir una breve descripción de la obra, como la descripción que aparece en la web, p.e.  http://www.medicapanamericana.com/Libros/Libro/5811/eBook-100-Tecnicas-de-Movilizacion-con-Impulso-en-Osteopatia.html 
@CristianBinpar

**Comment by minigoBinpar** [comment]
Ambos campos son iguales (en base de datos) y te admiten unos 1.073.741.823 caracteres aprox. Por pantalla se muestran distintos porque se trata de inducir al usuario una descripción breve y una sección notas donde explayarse.

Si quieres añadir nuevo campo crea issue y dime un poco longitud etc (pegame el enlace a pana para mejor ejemplo)

**Comment by MACEMP** [comment]
¿Podría visualizarse el campo DESCRIPCION como el campo NOTAS? Dispone de un "alargador" en la esquina inferior derecha que "tiras" y se hace más grande lo que permite ver el contenido completo de la nota.
Creo que no es necesario crear un nuevo campo.
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
se puede hacer el cambio

**Comment by minigoBinpar** [comment]
Ajustado:
![image](https://cloud.githubusercontent.com/assets/20515815/20520955/3962991a-b0a9-11e6-8758-6dcddc1972ce.png)
