### ISSUE TITLE
IMPRESIÓN PDF GENERADO: AUMENTAR EL TAMAÑO DE LETRA CUANDO SE IMPRIME

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#91]
Es una petición ya realizada y ahora hecha desde otras filiales. 
Solicitan que el PDF que se imprime tenga un tipo de letra más grande ya que resulta de difícil lectura.
@CristianBinpar

**Comment by minigoBinpar** [comment]
pongo a la gente de estilos sobre la pista y cuando tengan hueco vemos

**Comment by MACEMP** [comment]
Lo piden bastantes usuarios, y no solo los que usamos cristales progresivos :-)
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
[100.A.os.de.la.SERAM.pdf](https://github.com/BinPar/PPD/files/648872/100.A.os.de.la.SERAM.pdf)

:)

**Comment by MACEMP** [comment]
Fenomenal!
@minigoBinpar
