### ISSUE TITLE
USUARIO CON PERFIL EDITORIAL NO PUEDE INTRODUCIR DATO "FECHA DE PUBLICACION INICIAL"

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#93]
![image](https://cloud.githubusercontent.com/assets/22589031/20168900/c950e736-a724-11e6-91ba-7df729180251.png)
El usuario con perfil EDITORIAL tiene que poder editar todos los campos de fecha.

@CristianBinpar

**Comment by minigoBinpar** [comment]
Listo. Subo en 5 minutos
