### ISSUE TITLE
SERVICIO DE NOVEDAD: LA ORDENACION ALFABETICA DE LOS PRODUCTOS ES "CONFUSA"

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#94]
Los productos aparecen en el combo por orden alfabético del título, pero sin embargo el primer item que aparece es el de autor. Es mucho más lógico que la ordenación sea por orden alfabético autor, sobre todo porque no es un buscador inteligente como el de la HOME.
En la imagen se ve como aparecen cuando despliegas sin indicar ninguna búscqueda
![image](https://cloud.githubusercontent.com/assets/22589031/20171622/d871ed5c-a731-11e6-98b3-3d8d439f7574.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
El primer item es SAP. Esto se cambió hace poco. 

Creo recordar que hablamos el echo de que utilizar el nombre autor no garantizaba que apareciese el autor principal inicialmente (que es como identificais vosotros obras) porque si hay varios con el rol de director el programa no categoriza relevancia entre prioridades hermanas (esto está pendiente de desarrollo en otra issue)

**Comment by MACEMP** [comment]
Cierto, es SAP (facilita muchísimo el trabajo) Lo curioso es que la ordenación no la hace por la denominación SAP, si fuese así, aparecería por orden alfabético de autor  y el orden en el que aparece es en el del título de la obra dentro de la denominación SAP ¡extraño!
Si te fijas pone 2 veces la denominación SAP en cada producto.
@minigoBinpar

**Comment by minigoBinpar** [comment]
Correcto (buen ojo!) cambio para que ordene alfabeticamente por SAP y que solo aparezca una vez

**Comment by minigoBinpar** [comment]
Listo. Subo version a beta y pro
![Uploading image.png…]()
