### ISSUE TITLE
PLANTILLA PRESUPUESTO: FORMATOS CELDAS DESCARGADAS Y FORMULA ÚLTIMA COLUMNA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#95]
![image](https://cloud.githubusercontent.com/assets/22589031/20172983/98e15000-a737-11e6-8dbb-99f62313f02e.png)
En las celdas en las que aparecen las cantidades en DOLAR $ , el formato con el que se descarga el excel es GENERAL, no MONEDA por lo que no permite hacer cálculos. El formato MONEDA es el que se utiliza correctamente en el campo EUROS € y se descarga correctamente.
FORMULA ULTIMA COLUMNA : ¿cual es el % aplicado para calcular la última columna?
@CristianBinpar

**Comment by minigoBinpar** [comment]
0.7 vimos esta mañana en la reunión?

**Comment by MACEMP** [comment]
Si, lo vimos esta mañana. 
El campo en dólares no descarga el dato en formato moneda por lo que no se pueden hacer operaciones aritméticas con el. 
La pregunta de la fórmula ya está respondida. Calcula un descuento del 70% sobre el total en dólares.
@minigoBinpar

**Comment by minigoBinpar** [comment]
Bien. Cierro este issue porque la incidencia de las columnas con formato incorrecto lo tenemos abierto en la issue #12
