### ISSUE TITLE
PPD BETA: ERROR GUARDAR REPORTADO DESDE MEXICO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#97]
Desde México reportan este error al hacer pruebas en beta
**Intentamos hacer un  ejercicio de inicio a fin desde la creación de obra  hasta la incorporación de varios productos. Solo pudimos dar de alta la obra, ya no pudimos agregar productos, aparecía deshabilitado el botón de guardar.**

No tengo imagen para ilustrar el error. Utilizan Chrome.
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Necesitaría más datos. Tipo de producto, obra, datos a guardar... una captura de pantalla sería ideal.

Voy a hacer alguna prueba pero es ir un poco a ciegas

**Comment by MACEMP** [comment]
No me pasaron captura de pantalla. Ya he indicado que cuando se produzca un error me envíen una captura y faciliten más datos para poder replicar el caso.
Se que beta últimamente no responde correctamente. Durante la sesión de formación que hice con el Director General de Argentina, tuve algún que otro problema, que no pude reportar porque no era el momento de parar la sesión para hacer la captura de pantalla y la descripción del error.
@minigoBinpar

**Comment by minigoBinpar** [comment]
Entiendo. 
Sigo revisando a ver si encuentro algo. Estoy pensando que si hay gente trabajando con beta podría hacer una copia de producción y volcar en beta para tener los mismos datos. Le ves sentido a esto?

**Comment by MACEMP** [comment]
Me parece muy buena idea. 
Cuando lo hagas avíseme para que lo notifique a todos los usuarios para que no se sorprendan de encontrar en beta las mismas obras que en producción
@minigoBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
Bien. Cierro esta issue entonces, estamos atentos a reportes desde mex y abro otra issue para importar datos
