### ISSUE TITLE
PPD: ERROR GENERACIÓN PDF

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#98]
![image](https://cloud.githubusercontent.com/assets/22589031/20208125/3e562c90-a7ec-11e6-9061-542b08733fc8.png)
![image](https://cloud.githubusercontent.com/assets/22589031/20208155/78827c02-a7ec-11e6-8dca-c343a87990f4.png)

Al tratar de GENERAR PDF se obtiene respuesta de ERROR.
No se soluciona con ctrl+R varias veces y  ocurre tanto con EDGE como con CHROME
@CristianBinpar

**Comment by MACEMP** [comment]
Ya aparece el PDF, pero los campos no están vinculados. en la versión anterior se podía acceder rapidamente a cada una de las secciones.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
Solucionado. Vigilia que el block del navegador no nos esté jugando mala pasada como en el buscador de la home
