### ISSUE TITLE
PPD PRO_ERROR EN MENSAJE : INCORPORACION NUEVA OBRA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PPD#99]
![image](https://cloud.githubusercontent.com/assets/22589031/20208641/d1290ec2-a7ef-11e6-85b9-f90a737248a5.png)

El campo Especialidades secundarias aparece con ####WT#####

@CristianBinpar

**Comment by minigoBinpar** [comment]
Solucionado. Cuando no hay EspSec asignadas, muestra campo vacío. Proxima subida
![image](https://cloud.githubusercontent.com/assets/20515815/20313651/dfceabce-ab57-11e6-86c4-f2372b7b18e2.png)
